### PR TITLE
fix: checkSparkMaybeThrows should compare Spark and Comet results in success case

### LINKED ISSUE #2657: `checkSparkMaybeThrows` does not check for correct results in success case
### Describe the bug

`checkSparkMaybeThrows` does not verify that the results are correct when both Spark and Comet execute the query without error.

This could potentially be hiding correctness issues.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by andygrove**
## Which issue does this PR close?

Closes #2657

## What changes are included in this PR?

- Delegate to `checkSparkAnswer` in success case
- Rename method for consistency with other `checkSparkAnswer` methods

## How are these changes tested?

Existing tests

### CODE REVIEW

File: spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala [hunk 1]
```diff
@@ -316,8 +316,8 @@ abstract class CometTestBase
 
     (expected, actual) match {
       case (Success(_), Success(_)) =>
-        // TODO compare results and confirm that they match
-        // https://github.com/apache/datafusion-comet/issues/2657
+        // compare results and confirm that they match
+        checkSparkAnswer(df)
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala:320]: This is the fix. All other changes are for renaming the method.

**Comment by andygrove** [comment]
I am looking into this failure:

```
2025-11-07T16:55:12.8149030Z - cast ArrayType to StringType *** FAILED *** (23 seconds, 552 milliseconds)
2025-11-07T16:55:12.8293960Z   Results do not match for query:
```
