### PR TITLE
fix: handle ambiguous and non-existent local times

### LINKED ISSUE #3864: `timestamp_ntz_to_timestamp` panics on ambiguous or non-existent local times (DST transitions)
### Describe the bug

`timestamp_ntz_to_timestamp` panics when a local time is ambiguous or non-existent due to DST transitions:
- **Non-existent (spring forward):** e.g. `2024-03-31 01:30:00` in `Europe/London` — this time never occurs as clocks skip from 01:00 → 02:00, so `LocalResult::None` is returned and `from_local_datetime(...).unwrap()` panics.
- **Ambiguous (fall back):** e.g. `2024-10-27 01:30:00` in `Europe/London` — this time occurs twice as clocks repeat 01:00 → 02:00, so `LocalResult::Ambiguous` is returned and `from_local_datetime(...).unwrap()` panics.

Both the `TimestampMicrosecondType` and `TimestampMillisecondType` branches are affected.

### Steps to reproduce

```rust
// Non-existent time — spring forward
timestamp_ntz_to_timestamp(array_containing("2024-03-31 01:30:00"), "Europe/London", None); // panic!

// Ambiguous time — fall back
timestamp_ntz_to_timestamp(array_containing("2024-10-27 01:30:00"), "Europe/London", None); // panic!
```

### Expected behavior

The function should handle all `LocalResult` variants from `from_local_datetime(...)` without panicking. For ambiguous times, opt for the earlier option (consistent with e.g. Apache Spark). For a non-existent time, treat it like that time shifted an hour before.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by matthewalex4**
## Which issue does this PR close?

Closes #3864.

## Rationale for this change

`timestamp_ntz_to_timestamp` panics when a local time is ambiguous or non-existent due to DST transitions. Further explanation in issue description.

## What changes are included in this PR?

- The result of `from_local_datetime(...)` is handled for cases of ambiguous and non-existent local times.
- For ambiguous local times we choose the earlier option
- For non-existent local times we shift to an hour before, convert and shift back 

## How are these changes tested?

Unit tests provided for both ambiguous and non-existent local times.

### CODE REVIEW

File: native/spark-expr/src/utils.rs [hunk 1]
```diff
@@ -174,6 +174,19 @@ fn datetime_cast_err(value: i64) -> ArrowError {
     ))
 }
 
+fn resolve_local_datetime(tz: &Tz, local_datetime: NaiveDateTime) -> DateTime<Tz> {
+    match tz.from_local_datetime(&local_datetime) {
+        LocalResult::Single(dt) => dt,
+        LocalResult::Ambiguous(dt, _) => dt,
+        LocalResult::None => {
+            // Interpret nonexistent local time by shifting from one hour earlier.
+            let shift = TimeDelta::hours(1);
```
Comment (andygrove) [inline native/spark-expr/src/utils.rs]: The 1-hour shift works for standard DST transitions, but some timezones have non-standard gaps (e.g., Australia/Lord_Howe has a 30-minute DST transition). Yes, this is an edge case so it may be fine to ignore, but we should at least document this as an incompatibility.

https://www.timeanddate.com/time/change/australia/lord-howe-island

File: native/spark-expr/src/utils.rs [hunk 2]
```diff
@@ -330,4 +356,40 @@ mod tests {
         );
         assert_eq!(last, build_bool_state(&mut builder, &EmitTo::All));
     }
+
+    #[test]
+    fn test_timestamp_ntz_to_timestamp_handles_non_existent_time() {
+        let result = std::panic::catch_unwind(|| {
```
Comment (andygrove) [inline native/spark-expr/src/utils.rs]: do these tests still need `catch_unwind`?

**Comment by andygrove** [comment]
Thanks @matthewalex4. Could you also add an end-to-end Spark test, perhaps in `CometTemporalExpressionSuite`?

File: native/spark-expr/src/utils.rs (hunk 1 above)
Comment (matthewalex4) [reply native/spark-expr/src/utils.rs]: Added a comment in [d622e44](https://github.com/apache/datafusion-comet/pull/3865/commits/d622e447c030ca094789d65a9ea043f7ec6de83d)

File: native/spark-expr/src/utils.rs (hunk 2 above)
Comment (matthewalex4) [reply native/spark-expr/src/utils.rs]: No not necessary, removed in [d622e44](https://github.com/apache/datafusion-comet/pull/3865/commits/d622e447c030ca094789d65a9ea043f7ec6de83d)

**Comment by matthewalex4** [comment]
> Thanks @matthewalex4. Could you also add an end-to-end Spark test, perhaps in `CometTemporalExpressionSuite`?

Yes, have added a test in [998f975](https://github.com/apache/datafusion-comet/pull/3865/commits/998f97549d137cb7f505a457d5f766956355b33e)

File: native/spark-expr/src/utils.rs (hunk 1 above)
Comment (parthchandra) [reply native/spark-expr/src/utils.rs]: I'm handling the DST gap in https://github.com/apache/datafusion-comet/pull/3884. Perhaps you can wait for this to pass CI and then re-use.

File: spark/src/test/scala/org/apache/comet/CometTemporalExpressionSuite.scala [hunk 3]
```diff
@@ -489,4 +489,22 @@ class CometTemporalExpressionSuite extends CometTestBase with AdaptiveSparkPlanH
...
+      Row(java.time.LocalDateTime.parse("2024-10-27T01:30:00")) // Fall back (Europe/London)
+    )
+    val schema = StructType(Seq(StructField("ts_ntz", DataTypes.TimestampNTZType, true)))
+    spark
+      .createDataFrame(spark.sparkContext.parallelize(data), schema)
+      .createOrReplaceTempView("dst_tbl")
+
+    withSQLConf(
+      SQLConf.SESSION_LOCAL_TIMEZONE.key -> "Europe/London",
+      "spark.comet.expression.Cast.allowIncompatible" -> "true") {
```
Comment (parthchandra) [inline spark/src/test/scala/org/apache/comet/CometTemporalExpressionSuite.scala:507]: Can you add a comment why `allowIncompatible` is required here (because TimestampNTZ cast is classified as Incompatible due to issue #378/#3179)

File: native/spark-expr/src/utils.rs (hunk 1 above)
Comment (parthchandra) [reply native/spark-expr/src/utils.rs]: Consider doing something like in string.rs `parse_timestamp_to_micros`.  Something like - 
```
  LocalResult::None => {
      let probe = local_datetime - chrono::Duration::hours(3);
      let pre_offset = match tz.from_local_datetime(&probe) {
          LocalResult::Single(dt) => dt.offset().fix(),
          LocalResult::Ambiguous(dt, _) => dt.offset().fix(),
          // Cannot determine offset – return some safe fallback or propagate error
          LocalResult::None => {
              // Extreme edge case; fall back to UTC interpretation
              local_datetime.and_utc().with_timezone(tz)
          }
      };
      let offset_secs = pre_offset.local_minus_utc() as i64;
      let utc_naive = local_datetime - chrono::Duration::seconds(offset_secs);
      utc_naive.and_utc().with_timezone(tz)
  }
```
This eliminates the unwrap(), handles non-standard DST correctly, and reuses a pattern that already has test coverage in Comet.

File: spark/src/test/scala/org/apache/comet/CometTemporalExpressionSuite.scala (hunk 3 above)
Comment (matthewalex4) [reply spark/src/test/scala/org/apache/comet/CometTemporalExpressionSuite.scala:507]: Added in [76e3977](https://github.com/apache/datafusion-comet/pull/3865/commits/76e3977e7936098da6f0935687b2ae2d5b45f5a5)

**Review by parthchandra — APPROVED** [review]

**Comment by parthchandra** [comment]
Merged. Thank you @matthewalex4

**Comment by matthewalex4** [comment]
@andygrove @parthchandra Would it be possible for me to backport this fix to a release 0.14.1? We have a project that depends on datafusion version 52 and the availability of such a release would prevent us from needing to upgrade to datafusion 53. Thanks for your help.

**Comment by andygrove** [comment]
> @andygrove @parthchandra Would it be possible for me to backport this fix to a release 0.14.1? We have a project that depends on datafusion version 52 and the availability of such a release would prevent us from needing to upgrade to datafusion 53. Thanks for your help.

@matthewalex4  Sure. Could you create a PR to backport this PR to branch-0.14 ?

**Comment by andygrove** [comment]
> > @andygrove @parthchandra Would it be possible for me to backport this fix to a release 0.14.1? We have a project that depends on datafusion version 52 and the availability of such a release would prevent us from needing to upgrade to datafusion 53. Thanks for your help.
> 
> @matthewalex4 Sure. Could you create a PR to backport this PR to branch-0.14 ?

I went ahead created the backport PR - https://github.com/apache/datafusion-comet/pull/3937
