### PR TITLE
fix: [native_datafusion] only pass single partition of PartitionedFiles into DataSourceExec

### LINKED ISSUE #2660: [native_datafusion] Partition count mismatch when creating `HashJoinExec`
### Describe the bug

When using `native_datafusion` scan, we sometimes try and construct a `HashJoinExec` with different number of partitions for left and right inputs. This issue is currently hidden because we wrap the inputs in a `CopyExec` which always reports output partition count of 1.

Here is debug logging for one example. The left input has 5 partitions and the right input has 1 partition.

```
LEFT: FilterExec: c0@0 IS NOT NULL
  DataSourceExec: file_groups={5 groups: [[tmp/CometFuzzTestSuite_1761747873664.parquet/part-00002-e5c142ac-d0f8-4eb4-891c-4484865ded05-c000.snappy.parquet:0..133654], [tmp/CometFuzzTestSuite_1761747873664.parquet/part-00003-e5c142ac-d0f8-4eb4-891c-4484865ded05-c000.snappy.parquet:0..133566], [tmp/CometFuzzTestSuite_1761747873664.parquet/part-00000-e5c142ac-d0f8-4eb4-891c-4484865ded05-c000.snappy.parquet:0..133492], [tmp/CometFuzzTestSuite_1761747873664.parquet/part-00004-e5c142ac-d0f8-4eb4-891c-4484865ded05-c000.snappy.parquet:0..133471], [tmp/CometFuzzTestSuite_1761747873664.parquet/part-00001-e5c142ac-d0f8-4eb4-891c-4484865ded05-c000.snappy.parquet:0..132287]]}, projection=[c0], file_type=parquet, predicate=c0@0 IS NOT NULL, pruning_predicate=c0_null_count@1 != row_count@0, required_guarantees=[]

RIGHT: ScanExec: source=[BroadcastQueryStage (unknown), Statistics(sizeInBytes=1384.0 B, rowCount=1.00E+3)], schema=[col_0: Boolean]

```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mbutrovich**
## Which issue does this PR close?

Closes #2660.

## Rationale for this change

`DataSourceExec` bases its number of `target_partitions` on the size of the `Vec<Vec<PartitionedFiles>` passed into it, where the outer `Vec` size is the number of partitions and parallelism in the scan. We currently only execute the target partition so we get correct data results, but the operator still thinks its outputting `target_partitions` partitions, so we get a mismatch in downstream operators.

## What changes are included in this PR?

- Only extract `PartitionedFiles` for the target Spark partition and pass that into `DataSourceExec`
- Always execute partition 0 in DataFusion context (unsure about blast radius on this one, watching CI)

## How are these changes tested?

Existing tests, removed fallbacks referring to #2660.

### CODE REVIEW

File: native/core/src/execution/jni_api.rs [hunk 1]
```diff
@@ -485,12 +485,14 @@ pub unsafe extern "system" fn Java_org_apache_comet_Native_executePlan(
...
                 let task_ctx = exec_context.session_ctx.task_ctx();
+                // Each Comet native execution corresponds to a single Spark partition,
+                // so we should always execute partition 0.
                 let stream = exec_context
                     .root_op
                     .as_ref()
                     .unwrap()
                     .native_plan
-                    .execute(partition as usize, task_ctx)?;
+                    .execute(0, task_ctx)?;
```
Comment (andygrove) [inline native/core/src/execution/jni_api.rs:495]: This change could impact metrics, and we lack tests in this area. I am taking a look now to understand this better and see what we can do about it.

Comment (andygrove) [reply native/core/src/execution/jni_api.rs:495]: nm, this isn't an issue after all. ScanExec was already using partition 0 for most metrics.

**Review by andygrove — APPROVED** [review]
Thanks for the quick fix @mbutrovich!
