### PR TITLE
fix: format decimal to string when casting to short

### LINKED ISSUE #2914: `cast_decimal_to_int16_down` formats decimal value incorrectly
### Describe the bug

When implementing [fix: array to array cast](https://github.com/apache/datafusion-comet/pull/2897), the test of casting `ArrayType(DecimalType(10,2))` to `ArrayType(ShortType)` failed with following error, where comet formats `-96833550.07` to `-96833550.7DB`.

``` 
"...The value -96833550.[]7BD of the type "DEC..." did not equal "...The value -96833550.[0]7BD of the type "DEC..." (CometCastSuite.scala:1328)
```

It looks to be related to `cast_decimal_to_int16_down` 

https://github.com/apache/datafusion-comet/blob/5ec12d4024e78faa97834f88ab606ecd3d0db5fb/native/spark-expr/src/conversion_funcs/cast.rs#L674-L696

It can be proven by printing the original and truncated values.

```
casting value: -9683355007, truncated: -96833550, decimal: 7, is_overflow: false
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by manuzhang**
## Which issue does this PR close?

Closes #2914.

## How are these changes tested?

Updated CometCastSuite.

### CODE REVIEW

**Comment by manuzhang** [comment]
@rohitrastogi @andygrove Please help review when you find time. Thanks!

File: native/spark-expr/src/conversion_funcs/cast.rs [hunk 1]
```diff
@@ -755,11 +757,13 @@ macro_rules! cast_decimal_to_int32_up {
                 .map(|value| match value {
                     Some(value) => {
                         let divisor = 10_i128.pow($scale as u32);
-                        let (truncated, decimal) = (value / divisor, (value % divisor).abs());
+                        let truncated = value / divisor;
                         let is_overflow = truncated.abs() > $max_dest_val.into();
+                        let fmt_str =
```
Comment (wForget) [inline native/spark-expr/src/conversion_funcs/cast.rs]: Can this be moved into the `if is_overflow {..}` block?

Comment (manuzhang) [reply native/spark-expr/src/conversion_funcs/cast.rs]: Nope, `fmt_str` will be out of scope.

File: spark/src/test/scala/org/apache/comet/CometCastSuite.scala [hunk 2]
```diff
@@ -1030,7 +1030,9 @@ class CometCastSuite extends CometTestBase with AdaptiveSparkPlanHelper {
 
   test("cast between decimals with higher precision than source") {
     // cast between Decimal(10, 2) to Decimal(10,4)
-    castTest(generateDecimalsPrecision10Scale2(), DataTypes.createDecimalType(10, 4))
+    castTest(
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/comet/CometCastSuite.scala]: @manuzhang I pulled these test changes locally using latest from main branch and they pass for me, so I'm not sure that these tests reproduce the problem that the fix is intended to address?

Comment (manuzhang) [reply spark/src/test/scala/org/apache/comet/CometCastSuite.scala]: @andygrove I've reworked my PR. Could you please check again?

**Comment by manuzhang** [comment]
Failed test is not related to this PR.
```
- Comet native operator after ShuffleQueryStage + ReusedExchange (1 second, 108 milliseconds)
Error: Exception in thread "ScalaTest-dispatcher" java.lang.NoClassDefFoundError: $anonfun$doPreserve$1
	at org.scalatest.tools.PrettyPrinter.traverse(PrettyPrinter.scala:155)
	at org.scalatest.tools.PrettyPrinter.format(PrettyPrinter.scala:231)
	at org.scalatest.tools.PrettyPrinter.$anonfun$format$2(PrettyPrinter.scala:267)
	at org.scalatest.tools.PrettyPrinter.$anonfun$format$2$adapted(PrettyPrinter.scala:267)
	at org.scalatest.tools.XmlUtility$.sbToString(XmlUtility.scala:31)
	at org.scalatest.tools.PrettyPrinter.format(PrettyPrinter.scala:267)
	at org.scalatest.tools.JUnitXmlReporter.xmlify(JUnitXmlReporter.scala:385)
	at org.scalatest.tools.JUnitXmlReporter.writeSuiteFile(JUnitXmlReporter.scala:77)
	at org.scalatest.tools.JUnitXmlReporter.apply(JUnitXmlReporter.scala:59)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10(DispatchReporter.scala:249)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10$adapted(DispatchReporter.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:248)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: $anonfun$doPreserve$1
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 14 more
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (concurrentHashTable.inline.hpp:678), pid=78523, tid=28931
#  fatal error: aux_index does not match even or odd indices
#
# JRE version: OpenJDK Runtime Environment Zulu17.62+19-CRaC-CA (17.0.17+10) (build 17.0.17+10-LTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu17.62+19-CRaC-CA (17.0.17+10-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/runner/work/datafusion-comet/datafusion-comet/spark/hs_err_pid78523.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
#
```

File: native/spark-expr/src/conversion_funcs/cast.rs (hunk 1 above)
Comment (wForget) [reply native/spark-expr/src/conversion_funcs/cast.rs]: > Nope, `fmt_str` will be out of scope.

`fmt_str` seems to be needed only on error, we should avoid always creating it.

**Comment by manuzhang** [comment]
@andygrove @wForget Please help review again

File: spark/src/test/scala/org/apache/comet/CometCastSuite.scala (hunk 2 above)
Comment (wForget) [reply spark/src/test/scala/org/apache/comet/CometCastSuite.scala]: I verified locally that the newly added test case could reproduce the problem.

**Comment by wForget** [comment]
@manuzhang The `cast_decimal_to_int32_up` function also has a similar issue. Could you fix it as well?

Reproduce test case:

```
    castTest(
      generateDecimalsPrecision38Scale18(Seq(BigDecimal("-99999999999999999999.07"))),
      DataTypes.LongType)
```

error:

```
"...9999999999999999999.[]70000000000000000BD ..." did not equal "...9999999999999999999.[0]70000000000000000BD ..."
```

**Comment by manuzhang** [comment]
@wForget Thanks for the good suggestion. I was struggling with test case so I left the changes to `cast_decimal_to_int32_up` out. I've added tests for `cast DecimalType(38,18) to ShortType/IntegerType/LongType`.

**Comment by wForget** [comment]
Thanks @manuzhang, merged to main
