### PR TITLE
fix: Cast string to boolean not compatible with Spark

### LINKED ISSUE #17: Cast string to boolean not compatible with Spark
```
scala> import org.apache.spark.sql.types._
import org.apache.spark.sql.types._

scala> val inputs = Seq("TR", "FA").toDF("n")
inputs: org.apache.spark.sql.DataFrame = [n: string]

scala> inputs.write.parquet("test.parquet")
24/02/13 07:58:44 INFO src/lib.rs: Comet native library initialized
                                                                                
scala> val df = spark.read.parquet("test.parquet")
df: org.apache.spark.sql.DataFrame = [n: string]

scala> val df2 = df.withColumn("converted", col("n").cast(DataTypes.BooleanType))
df2: org.apache.spark.sql.DataFrame = [n: string, converted: boolean]

scala> df2.show
+---+---------+                                                                 
|  n|converted|
+---+---------+
| FA|    false|
| TR|     true|
+---+---------+

scala> spark.conf.set("spark.comet.enabled", false)

scala> df2.show
+---+---------+
|  n|converted|
+---+---------+
| FA|     null|
| TR|     null|
+---+---------+
```

### PR DESCRIPTION
**Pull request by erenavsarogullari**
## Which issue does this PR close?

Closes #17.

## Rationale for this change

Comet needs to be compatible with Spark on string to boolean casting results.

## What changes are included in this PR?

Currently, Spark supports following boolean values and Comet also needs to compatible with Spark.
```
trueStrings => "t", "true", "y", "yes", "1"
falseStrings => "f", "false", "n", "no", "0"
```
Spark Reference API:
https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/StringUtils.scala#L74
https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/Cast.scala#L585
Note: I will also add `spark.sql.ansi.enabled` case support.

## How are these changes tested?

Added new UT.

### CODE REVIEW

File: spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala [hunk 1]
```diff
@@ -218,6 +220,51 @@ class CometExecSuite extends CometTestBase {
     }
   }
 
+  test("test cast utf8 to boolean as compatible with Spark") {
```
Comment (viirya) [inline spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala:223]: I think `CometExpressionSuite` is more proper place for the test?

**Comment by viirya** [comment]
> Note: I will also add spark.sql.ansi.enabled case support.

Comet doesn't support ansi enabled case for now. I think we can ignore them first.

File: spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala (hunk 1 above)
Comment (erenavsarogullari) [reply spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala]: Thanks @viirya for quick review. Yes, makes sense, addressed.

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 2]
```diff
@@ -1302,4 +1304,50 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
+      CometConf.COMET_EXEC_ALL_OPERATOR_ENABLED.key -> "true") {
+      withTable("test_table1", "test_table2", "test_table3", "test_table4") {
+        // Supported boolean values as true by both Arrow and Spark
+        val inputDF = Seq("t", "true", "y", "yes", "1", "T", "TrUe", "Y", "YES").toDF("c1")
+        inputDF.write.format("parquet").saveAsTable("test_table1")
+        val resultDF = this.spark
+          .table("test_table1")
+          .withColumn("converted", col("c1").cast(DataTypes.BooleanType))
+        val resultArr = resultDF.collectAsList().toList
+        resultArr.foreach(x => assert(x.get(1) == true))
```
Comment (viirya) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:1320]: Besides this, we can use `checkSparkAnswerAndOperator` to check if the result is same as Spark.

File: core/src/execution/datafusion/expressions/cast.rs [hunk 3]
```diff
@@ -75,8 +75,40 @@ impl Cast {
...
-        Ok(spark_cast(cast_result, from_type, &self.data_type))
+        let to_type = &self.data_type;
+        let cast_result = match (from_type, to_type) {
+            (DataType::Utf8, DataType::Boolean) => Self::spark_cast_utf8_to_boolean::<i32>(&array),
+            (DataType::LargeUtf8, DataType::Boolean) => {
+                Self::spark_cast_utf8_to_boolean::<i64>(&array)
+            }
+            _ => cast_with_options(&array, &self.data_type, &CAST_OPTIONS)?,
+        };
+        let result = spark_cast(cast_result, from_type, &self.data_type);
```
Comment (viirya) [inline core/src/execution/datafusion/expressions/cast.rs:86]:
```suggestion
        let result = spark_cast(cast_result, from_type, to_type);
```

File: core/src/execution/datafusion/expressions/cast.rs [hunk 4]
```diff
@@ -75,8 +75,40 @@ impl Cast {
...
         let from_type = array.data_type();
-        let cast_result = cast_with_options(&array, &self.data_type, &CAST_OPTIONS)?;
-        Ok(spark_cast(cast_result, from_type, &self.data_type))
+        let to_type = &self.data_type;
+        let cast_result = match (from_type, to_type) {
+            (DataType::Utf8, DataType::Boolean) => Self::spark_cast_utf8_to_boolean::<i32>(&array),
+            (DataType::LargeUtf8, DataType::Boolean) => {
+                Self::spark_cast_utf8_to_boolean::<i64>(&array)
+            }
+            _ => cast_with_options(&array, &self.data_type, &CAST_OPTIONS)?,
```
Comment (viirya) [inline core/src/execution/datafusion/expressions/cast.rs:84]:
```suggestion
            _ => cast_with_options(&array, to_type, &CAST_OPTIONS)?,
```

File: core/src/execution/datafusion/expressions/cast.rs [hunk 5]
```diff
@@ -75,8 +75,40 @@ impl Cast {
...
         let array = array_with_timezone(array, self.timezone.clone(), Some(&self.data_type));
         let from_type = array.data_type();
-        let cast_result = cast_with_options(&array, &self.data_type, &CAST_OPTIONS)?;
-        Ok(spark_cast(cast_result, from_type, &self.data_type))
+        let to_type = &self.data_type;
+        let cast_result = match (from_type, to_type) {
+            (DataType::Utf8, DataType::Boolean) => Self::spark_cast_utf8_to_boolean::<i32>(&array),
+            (DataType::LargeUtf8, DataType::Boolean) => {
+                Self::spark_cast_utf8_to_boolean::<i64>(&array)
+            }
```
Comment (viirya) [inline core/src/execution/datafusion/expressions/cast.rs:83]: We probably need to handle dictionary types too. Maybe as a follow up.

Comment (erenavsarogullari) [reply core/src/execution/datafusion/expressions/cast.rs:83]: Is this for casting from `Dictionary.value_type` to `Boolean`?

Comment (viirya) [reply core/src/execution/datafusion/expressions/cast.rs:83]: Yea

Comment (viirya) [reply core/src/execution/datafusion/expressions/cast.rs:83]: i.e., `Dictionary(_, DataType::Utf8)` and `Dictionary(_, DataType:: LargeUtf8)`

Comment (erenavsarogullari) [reply core/src/execution/datafusion/expressions/cast.rs:83]: Sure, please feel free to create an issue so i can have a look after this PR. Thanks

**Review by viirya — APPROVED** [review]

**Review by sunchao — APPROVED** [review]

**Comment by sunchao** [comment]
Merged, thanks!
