### PR TITLE
fix: make tan and atan2 compatible

### LINKED ISSUE #1897: tan(-0.0) produces incorrect result
### Describe the bug

While working on https://github.com/apache/datafusion-comet/pull/1896 I discovered that `tan(-0.0)` produces an incorrect result.

```
3.141592653589793 was not less than 1.0E-6 actual answer -3.141592653589793 not within 1.0E-6 of correct answer 0.0
```

### Steps to reproduce

Uncomment the `-0.0` in the test data in https://github.com/apache/datafusion-comet/pull/1896 and run the tests

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kazuyukitanimura**
## Which issue does this PR close?

Closes: #1897

## Rationale for this change

#1897 claims `tan` is incompatible; however, what is really incompatible is `atan2` that is failing in the same test in #1896

The correct results are
```
 atan2(-0.0, -0.0) =  -π    <= Comet answer
 atan2(-0.0, +0.0) = -0.0
 atan2(+0.0, -0.0) = +π
 atan2(+0.0, +0.0) = +0.0   <= Spark answer
```
Looks like Spark adds `+0.0` to inputs in order to convert `atan2(-0.0, -0.0)` to ` atan2(+0.0, +0.0)`

## What changes are included in this PR?

Fixed `atan2` and enabled `tan`

### CODE REVIEW

**Comment by andygrove** [comment]
Thanks @kazuyukitanimura. Could you add SQL file based tests, since this is preferred approach now. See https://github.com/apache/datafusion-comet/pull/3854 for example.

**Comment by kazuyukitanimura** [comment]
> Thanks @kazuyukitanimura. Could you add SQL file based tests, since this is preferred approach now. See #3854 for example.

Thanks @andygrove, updated spark/src/test/resources/sql-tests/expressions/math/atan2.sql

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 1]
```diff
@@ -1346,7 +1345,7 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
 
   test("various math scalar functions") {
     val data = doubleValues.map(n => (n, n))
-    withSQLConf(CometConf.getExprAllowIncompatConfigKey(classOf[Tan]) -> "true") {
+    withSQLConf() {
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala]: Empty `withSQLConf()` can be removed?

File: spark/src/main/scala/org/apache/comet/serde/math.scala [hunk 2]
```diff
@@ -213,24 +219,6 @@ object CometAbs extends CometExpressionSerde[Abs] with MathExprBase {
   }
 }
 
-object CometTan extends CometExpressionSerde[Tan] {
-
-  override def getSupportLevel(expr: Tan): SupportLevel =
-    Incompatible(
-      Some(
-        "tan(-0.0) produces incorrect result" +
```
Comment (andygrove) [inline spark/src/main/scala/org/apache/comet/serde/math.scala:197]: could you add a test to `tan.sql` to confirm that this now produces the same results as Spark?

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala (hunk 1 above)
Comment (kazuyukitanimura) [reply spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala]: removed

File: spark/src/main/scala/org/apache/comet/serde/math.scala (hunk 2 above)
Comment (kazuyukitanimura) [reply spark/src/main/scala/org/apache/comet/serde/math.scala:197]: added

File: spark/src/main/scala/org/apache/comet/serde/math.scala [hunk 3]
```diff
@@ -19,13 +19,19 @@
...
 import org.apache.spark.sql.types.{DecimalType, DoubleType, NumericType}
 
 import org.apache.comet.CometSparkSessionExtensions.withInfo
 import org.apache.comet.serde.QueryPlanSerde.{exprToProtoInternal, optExprWithInfo, scalarFunctionExprToProto, scalarFunctionExprToProtoWithReturnType, serializeDataType}
 
 object CometAtan2 extends CometExpressionSerde[Atan2] {
+  override def getSupportLevel(expr: Atan2): SupportLevel =
+    Incompatible(
+      Some(
+        "atan2(-0.0, -0.0) produces incompatible result" +
```
Comment (comphead) [inline spark/src/main/scala/org/apache/comet/serde/math.scala]: if it is only 1 input value which returns incorrect response, should we just hardcode the response?

Comment (kazuyukitanimura) [reply spark/src/main/scala/org/apache/comet/serde/math.scala]: Can done separately. I haven't decided how we should handle this. Because this is more like Spark side issue.

Comment (kazuyukitanimura) [reply spark/src/main/scala/org/apache/comet/serde/math.scala]: Actually we need do more tests for atan2 to enable e.g.
```
 atan2(-0.0, -0.0) 
 atan2(-0.0, +0.0)
 atan2(+0.0, -0.0)
 atan2(+0.0, +0.0)
 atan2(-0.0, -1.0) 
 atan2(-1.0, -0.0)
 atan2(-0.0, +1.0)
 atan2(+1.0, -0.0)
...
```

Comment (kazuyukitanimura) [reply spark/src/main/scala/org/apache/comet/serde/math.scala]: @comphead I ended up fixing `atan2` as well. Please take a look

File: spark/src/test/resources/sql-tests/expressions/math/atan2.sql [hunk 4]
```diff
@@ -21,7 +21,15 @@ statement
 CREATE TABLE test_atan2(y double, x double) USING parquet
 
 statement
-INSERT INTO test_atan2 VALUES (0.0, 1.0), (1.0, 0.0), (1.0, 1.0), (-1.0, -1.0), (0.0, 0.0), (NULL, 1.0), (1.0, NULL), (cast('NaN' as double), 1.0), (cast('Infinity' as double), 1.0)
+INSERT INTO test_atan2 VALUES
+  (0.0, 0.0), (0.0, -0.0), (0.0, 1.0), (0.0, -1.0), (0.0, NULL), (0.0, cast('NaN' as double)), (0.0, cast('Infinity' as double)), (0.0, cast('-Infinity' as double)),
```
Comment (comphead) [inline spark/src/test/resources/sql-tests/expressions/math/atan2.sql:25]: nice permutations

**Review by comphead — APPROVED** [review]
Thanks @kazuyukitanimura this is LGTM

**Comment by kazuyukitanimura** [comment]
Thank you @comphead merged
