### PR TITLE
fix: Support on all-literal RLIKE expression

### LINKED ISSUE #3343: Native engine crashes on all-literal RLIKE expression
## Description

When Spark's `ConstantFolding` optimizer rule is disabled, an all-literal `RLIKE` expression reaches the native engine, which crashes with:

```
non scalar regexp patterns are not supported.
```

The error message is misleading — the issue is that both the input string and the pattern are scalar literals.

## How to Reproduce

```sql
SET spark.sql.optimizer.excludedRules=org.apache.spark.sql.catalyst.optimizer.ConstantFolding;
SET spark.comet.regexp.allowIncompatible=true;
SELECT 'hello' RLIKE '^[a-z]+$';
```

## Expected Behavior

The native engine should handle all-scalar RLIKE inputs gracefully — either by computing the correct result or by falling back to Spark.

### PR DESCRIPTION
**Pull request by 0lai0**
## Which issue does this PR close?

Closes #3343 

## Rationale for this change

When `ConstantFolding` is disabled, all-literal RLIKE expressions crash the native engine with a misleading error. The engine should handle scalar literals gracefully.

## What changes are included in this PR?

- Fixed all-literal RLIKE expression handling in native engine
- Added proper scalar evaluation for RLIKE with literal inputs
- Improved error handling and fallback logic
## How are these changes tested?

- Added tests for all-literal RLIKE with `ConstantFolding` disabled
- Verified `rlike_enabled.sql` test now passes
- All existing RLIKE tests continue to pass
- `./mvnw test -Dsuites="org.apache.comet.CometSqlFileTestSuite rlike_enabled" -Dtest=none`

### CODE REVIEW

File: native/spark-expr/src/predicate_funcs/rlike.rs [hunk 1]
```diff
@@ -140,8 +140,30 @@ impl PhysicalExpr for RLike {
...
+                    // NULL RLIKE pattern -> NULL result
+                    return Ok(ColumnarValue::Scalar(ScalarValue::Boolean(None)));
+                }
+
+                // Extract string value from scalar and match pattern
+                // We handle each type separately to avoid lifetime issues with Utf8View
+                let is_match = match scalar {
+                    ScalarValue::Utf8(Some(s)) => self.pattern.is_match(s.as_str()),
+                    ScalarValue::LargeUtf8(Some(s)) => self.pattern.is_match(s.as_str()),
+                    ScalarValue::Utf8View(Some(s)) => self.pattern.is_match(s.as_str()),
```
Comment (coderfender) [inline native/spark-expr/src/predicate_funcs/rlike.rs]: @0lai0 would we ever get a `UTF8View` input from the spark side?

File: native/spark-expr/src/predicate_funcs/rlike.rs [hunk 2]
```diff
@@ -140,8 +140,30 @@ impl PhysicalExpr for RLike {
...
+                    _ => {
+                        return internal_err!(
```
Comment (coderfender) [inline native/spark-expr/src/predicate_funcs/rlike.rs:153]: @0lai0 could we also add test on rust side ?

**Review by coderfender — COMMENTED** [review]
Thank you for adding additional support. Left couple of comments

File: native/spark-expr/src/predicate_funcs/rlike.rs (hunk 1 above)
Comment (0lai0) [reply native/spark-expr/src/predicate_funcs/rlike.rs]: Yes, On the current Spark -> Comet proto -> native planner path, string literals are deserialized as ScalarValue::Utf8. So I think keeping Utf8 handling here is necessary. 
Let me know if I missed anything.

File: native/spark-expr/src/predicate_funcs/rlike.rs (hunk 2 above)
Comment (0lai0) [reply native/spark-expr/src/predicate_funcs/rlike.rs:153]: Sure, thanks @coderfender.

File: native/spark-expr/src/predicate_funcs/rlike.rs [hunk 3]
```diff
@@ -21,7 +21,9 @@ use arrow::array::types::Int32Type;
 use arrow::array::{Array, BooleanArray, DictionaryArray, RecordBatch, StringArray};
 use arrow::compute::take;
 use arrow::datatypes::{DataType, Schema};
-use datafusion::common::{internal_err, Result};
+use datafusion::common::{internal_err, Result, ScalarValue};
+#[cfg(test)]
+use datafusion::physical_expr::expressions::Literal;
```
Comment (andygrove) [inline native/spark-expr/src/predicate_funcs/rlike.rs]: The import should just be moved inside `mod test` which is already behind the `#[cfg(test)]` guard

**Comment by 0lai0** [comment]
Thanks @andygrove for the review. PR updated.

File: native/spark-expr/src/predicate_funcs/rlike.rs [hunk 4]
```diff
@@ -165,3 +181,26 @@ impl PhysicalExpr for RLike {
...
+
+#[cfg(test)]
+mod tests {
+    use super::*;
+    use datafusion::physical_expr::expressions::Literal;
+
+    #[test]
+    fn test_rlike_scalar_utf8_literal() {
+        let expr = RLike::try_new(
+            Arc::new(Literal::new(ScalarValue::Utf8(Some("Rose".to_string())))),
```
Comment (martin-g) [inline native/spark-expr/src/predicate_funcs/rlike.rs]: This tests the happy path (`Utf8(Some)`).
It would be good to also add a test case for `Utf8(None)`.

You could also extend it to cover the LargeUtf8 and Utf8View paths too:
```rust
for scalar in &[ScalarValue::Utf8(Some("Utf8".to_string())), ScalarValue::LargeUtf8(Some("LargeUtf8".to_string())), ScalarValue::Utf8View(Some("Utf8View".to_string()))] { ... }
```

and some non-Utf8 type, e.g. ScalarValue::Boolean to trigger the error.

File: native/spark-expr/src/predicate_funcs/rlike.rs [hunk 5]
```diff
@@ -140,8 +140,24 @@ impl PhysicalExpr for RLike {
...
-                internal_err!("non scalar regexp patterns are not supported")
+            ColumnarValue::Scalar(scalar) => {
+                if scalar.is_null() {
+                    return Ok(ColumnarValue::Scalar(ScalarValue::Boolean(None)));
+                }
+
+                let is_match = match scalar {
+                    ScalarValue::Utf8(Some(s))
+                    | ScalarValue::LargeUtf8(Some(s))
+                    | ScalarValue::Utf8View(Some(s)) => self.pattern.is_match(s.as_str()),
```
Comment (martin-g) [inline native/spark-expr/src/predicate_funcs/rlike.rs]:
```suggestion
                    | ScalarValue::Utf8View(Some(s)) => self.pattern.is_match(&s),
```

File: native/spark-expr/src/predicate_funcs/rlike.rs (hunk 4 above)
Comment (0lai0) [reply native/spark-expr/src/predicate_funcs/rlike.rs]: Thanks @martin-g PR updated.

**Comment by martin-g** [comment]
Thank you, @0lai0 !

**Comment by 0lai0** [comment]
Thanks @coderfender , @andygrove and @martin-g
