### PR TITLE
fix: report task output metrics in Spark UI

### LINKED ISSUE #3608: Native writer doesn't report written bytes
Native writer doesnt report written bytes in Spark UI

Image

For stageId 2 the `Ouput` tab should contain written bytes

### PR DESCRIPTION
**Pull request by 0lai0**
## Which issue does this PR close?

Part of #3996 
Closes #3608 

## Rationale for this change

Native Parquet writes executed by Comet were updating SQL metrics (bytes_written, rows_written) but not Spark task-level OutputMetrics. Spark UI Stages displays the Output column from task metrics, so native write stages could show empty output even when files were successfully written.
This change aligns native write metrics reporting with Spark UI expectations by propagating native write totals to task-level output metrics.

## What changes are included in this PR?

- Add reportNativeWriteOutputMetrics in CometMetricNode to bridge native writer SQL metrics to Spark task-level OutputMetrics (bytesWritten, recordsWritten) at task completion.
- Register this reporting hook in CometNativeWriteExec before creating CometExecIterator, so final native metric updates are available when completion listeners run.

## How are these changes tested?

Added/ran targeted ScalaTest
image

### CODE REVIEW

File: spark/src/test/scala/org/apache/spark/sql/comet/CometTaskMetricsSuite.scala [hunk 1]
```diff
@@ -100,6 +105,73 @@ class CometTaskMetricsSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
+            try {
+              sql("SELECT * FROM tbl").write.parquet(outPath)
+            } finally {
+              spark.sparkContext.clearJobGroup()
+            }
+          }
+
+          spark.sparkContext.listenerBus.waitUntilEmpty()
+
+          assert(outputBytes.nonEmpty, "No task reported outputMetrics.bytesWritten")
```
Comment (comphead) [inline spark/src/test/scala/org/apache/spark/sql/comet/CometTaskMetricsSuite.scala:166]: Please check the test for input metrics, we def need to ensure number of rows are the same. for bytes we need to have some approximation

Comment (0lai0) [reply spark/src/test/scala/org/apache/spark/sql/comet/CometTaskMetricsSuite.scala:166]: Sure, I'll update in next commit. Thanks @comphead for review.

Comment (0lai0) [reply spark/src/test/scala/org/apache/spark/sql/comet/CometTaskMetricsSuite.scala:166]: Updated. Now assert recordsWritten with exact equality, and use the existing suite convention for bytes approximation (ratio in 0.7–1.3), consistent with other input-metrics checks in CometTaskMetricsSuite.

**Review by comphead — APPROVED** [review]
Thanks @0lai0 it is LGTM
