### PR TITLE
Avoid duplicated writer nodes when AQE enabled

### LINKED ISSUE #2971: Comet writer executes twice
### Describe the bug

Comet writes executes twice with AQE 

Image

```
== Physical Plan ==
AdaptiveSparkPlan (8)
+- == Final Plan ==
   CometNativeWrite (5)
   +- CometNativeWrite (4)
      +- ShuffleQueryStage (3), Statistics(sizeInBytes=9.5 KiB, rowCount=1.00E+3)
         +- CometExchange (2)
            +- CometScan [native_iceberg_compat] parquet  (1)
+- == Initial Plan ==
   CometNativeWrite (7)
   +- CometExchange (6)
      +- CometScan [native_iceberg_compat] parquet  (1)
```

### Steps to reproduce

Folder `output3` doesn't exist

```
spark.read.parquet("/tmp/writertest/input").repartition(1).write.mode("overwrite").parquet("/tmp/writertest/output3")
```

### Expected behavior

Should write only once

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by comphead**
## Which issue does this PR close?

Closes #2971 .

## Rationale for this change

Comet executed the write twice when AQE enabled, the write should be done only once. The reason was the AQE runs its set of rules and applies modifications based on original plan and looks for `WriteFilesExec` or `DataWriteCommandExec`. Those command were replaced by Comet and AQE inserts another write layer on top of Comet layer

### CODE REVIEW

File: spark/src/test/scala/org/apache/comet/parquet/CometParquetWriterSuite.scala [hunk 1]
```diff
@@ -97,20 +98,25 @@ class CometParquetWriterSuite extends CometTestBase {
...
+              case _ =>
             }
-          case _ => false
+          case _ =>
         }
 
         assert(
-          hasNativeWrite,
-          s"Expected CometNativeWriteExec in the plan, but got:\n${executedPlan.treeString}")
+          nativeWriteCount == 1,
```
Comment (comphead) [inline spark/src/test/scala/org/apache/comet/parquet/CometParquetWriterSuite.scala:118]: check the count is just 1
