### PR TITLE
fix: NativeScan count assert firing for no reason

### LINKED ISSUE #2849: NativeScan count assertion fires needleslly
### Describe the bug

If I have 
```
        Aggregate
          Union
NativeScan    NativeScan
```
There is no reason for this assertion to fire, those native scans are in completely different comet plans and their hadoopConfs do not interfere with each other.

The union has its own executeColumnar, so does not go through that path, but the moment another native exec is after the union this happens

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by EmilyMatt**
## Which issue does this PR close?

Closes #2849 .

## Rationale for this change

The error was fired needlessly, for something that could be fully supported

## What changes are included in this PR?

Instead of collecting leaves, we only need to collect NativeScanExecs up until all CometInputs

## How are these changes tested?

Modified the original union test to actually check this

### CODE REVIEW

**Comment by EmilyMatt** [comment]
Updated the PR to not fire the assertion at all if no encryption options exist, as I see no benefit in just forbidding using more than 1 native scan unless more than 1 of them requires decryption

File: spark/src/main/scala/org/apache/spark/sql/comet/operators.scala [hunk 1]
```diff
@@ -217,22 +217,14 @@ abstract class CometNativeExec extends CometExec {
         // TODO: support native metrics for all operators.
         val nativeMetrics = CometMetricNode.fromCometPlan(this)
 
+        // Go over all all the native scans, in order to see if they need encryption options.
```
Comment (mbutrovich) [inline spark/src/main/scala/org/apache/spark/sql/comet/operators.scala]: typo: "all all"

File: spark/src/test/scala/org/apache/spark/sql/comet/ParquetEncryptionITCase.scala [hunk 2]
```diff
@@ -394,53 +395,60 @@ class ParquetEncryptionITCase extends CometTestBase with SQLTestUtils {
...
-        val readDataset = parquetDF.select("a", "b", "c")
-
-        // native_datafusion and native_iceberg_compat fall back due to Arrow-rs not
-        // supporting other key lengths
-        if (CometConf.COMET_ENABLED.get(conf) && CometConf.COMET_NATIVE_SCAN_IMPL.get(
-            conf) == SCAN_NATIVE_COMET) {
-          checkSparkAnswerAndOperator(readDataset)
-        } else {
-          checkAnswer(readDataset, inputDF)
+    test("Test different key lengths") {
```
Comment (mbutrovich) [inline spark/src/test/scala/org/apache/spark/sql/comet/ParquetEncryptionITCase.scala]: Did a formatting change cause the diff for "Test different key lengths"?

Comment (EmilyMatt) [reply spark/src/test/scala/org/apache/spark/sql/comet/ParquetEncryptionITCase.scala]: I'm not sure ;-;
I'm honestly really suffering with the formatting and testing in Comet, I will not lie :sweat_smile: Probably with mvn in general
I will try and fix this

File: spark/src/main/scala/org/apache/spark/sql/comet/operators.scala (hunk 1 above)
Comment (EmilyMatt) [reply spark/src/main/scala/org/apache/spark/sql/comet/operators.scala]: Will fix :)

**Comment by EmilyMatt** [comment]
> Minor comment nit. Thanks for the fix @EmilyMatt!
> 
> I am incredibly curious: are you using PME with Comet successfully?

I have not tried it actually, as for my use case I haven't ever needed encryption^^
But I do prefer using native_datafusion as it proves to be faster, and this just broke 2 cases of mine (1 where I use SMJ, and 1 with Union)
In general I think instead of broadcasting the config should just be serialized as part of the operator itself, as this seems to break some important functionality^

File: spark/src/test/scala/org/apache/spark/sql/comet/ParquetEncryptionITCase.scala (hunk 2 above)
Comment (EmilyMatt) [reply spark/src/test/scala/org/apache/spark/sql/comet/ParquetEncryptionITCase.scala]: Ok it was something with the SQLConf I attempted to add

**Comment by EmilyMatt** [comment]
@mbutrovich i believe the only failing test was due to some 500 when fetching a package

**Review by mbutrovich — APPROVED** [review]
Thanks @EmilyMatt!
