### PR TITLE
fix: Correct GetArrayItem null handling for dynamic indices and re-enable native execution

### LINKED ISSUE #3330: GetArrayItem returns wrong results (off-by-one index)
## Description

The `get_array_item.sql` SQL file test reveals incorrect results from the native `GetArrayItem` implementation.

## Expected vs Actual

```
== Correct Answer ==      == Spark Answer ==
struct<arr[idx]:int>      struct<arr[idx]:int>
[10]                      [10]
[1]                       [10]   <-- wrong
[20]                      [1]
[30]                      [20]
[null]                    [30]
[null]                    [null]
```

The results are shifted — it appears the first row's value is duplicated and subsequent rows use the previous row's index. This suggests an off-by-one or stale-index bug in the native `GetArrayItem` evaluation.

## Reproduction

Run `CometSqlFileTestSuite` — the `get_array_item.sql` test fails with both `parquet.enable.dictionary=false` and `true`.

### LINKED ISSUE #3332: GetArrayItem returns incorrect results with dynamic index
## Description

`GetArrayItem` (i.e., `arr[idx]` where `idx` is a column reference rather than a literal) returns results in incorrect order.

## How to reproduce

```sql
CREATE TABLE test_get_array_item(arr array<int>, idx int) USING parquet;
INSERT INTO test_get_array_item VALUES (array(10, 20, 30), 0), (array(10, 20, 30), 1), (array(10, 20, 30), 2), (array(1), 0), (NULL, 0), (array(10, 20), NULL);
SELECT arr[idx] FROM test_get_array_item;
```

### Expected results
```
[10]
[20]
[30]
[1]
[null]
[null]
```

### Actual results
```
[10]
[10]
[1]
[20]
[30]
[null]
```

The results appear to be returned in an incorrect order.

Found via `CometSqlFileTestSuite` running `expressions/array/get_array_item.sql`.

### PR DESCRIPTION
**Pull request by 0lai0**
## Which issue does this PR close?

Closes #3332 
Closes #3330

## Rationale for this change

Previously, list_extract.rs iterated over index_array.values(), which returns the raw Arrow buffer (&[i32]). In the Arrow memory format, the underlying buffer for NULL slots contains undefined/garbage values (typically 0). When arr[idx] was evaluated and idx was NULL, Comet incorrectly read this default 0 value instead of checking the validity bitmap, resulting in arr[0] being returned instead of NULL.

By switching to index_array.iter(), which returns an Option<i32>, we can safely use pattern matching to handle None correctly and append nulls to the output array without touching the garbage data.

## What changes are included in this PR?

This PR fixes a correctness bug in the native execution of GetArrayItem when dealing with dynamic indices containing NULL values. It also removes the Incompatible fallback workaround, fully re-enabling native execution for this expression.

The following changes were made:

1. Rust Core Fix (list_extract.rs): Replaced index_array.values() with index_array.iter().

2. Remove Workaround (arrays.scala): Removed the getSupportLevel override in CometGetArrayItem that forced fallback to Spark.

3. Test Cleanup:
     - Re-enabled the SQL test in get_array_item.sql by changing query ignore to query spark_answer_only.

     - Removed the now-unnecessary allowIncompatible configuration for GetArrayItem across CometExpressionSuite, CometNativeReaderSuite, and ParquetReadSuite.

## How are these changes tested?

- Existing tests in get_array_item.sql have been un-ignored and now successfully pass against the Spark answers.

- `make test` executed to ensure no regressions in native arrays/list extraction handling.

### CODE REVIEW

File: spark/src/test/resources/sql-tests/expressions/array/get_array_item.sql [hunk 1]
```diff
@@ -26,7 +26,7 @@ INSERT INTO test_get_array_item VALUES (array(10, 20, 30), 0), (array(10, 20, 30
 query spark_answer_only
 SELECT arr[0], arr[1], arr[2] FROM test_get_array_item
 
-query ignore(https://github.com/apache/datafusion-comet/issues/3332)
+query spark_answer_only
```
Comment (andygrove) [inline spark/src/test/resources/sql-tests/expressions/array/get_array_item.sql]: Why is this `spark_answer_only`? Seems like this should work in Comet now?

Comment (0lai0) [reply spark/src/test/resources/sql-tests/expressions/array/get_array_item.sql]: Got it! Thanks @andygrove for the reminder. Since the bug is fixed and the Incompatible marking is removed, GetArrayItem should now run natively in Comet. I've updated all three queries to use the default mode.
