### PR TITLE
Test: Add test coverage and documentation for SumDecimal/AvgDecimal nullability behavior

### LINKED ISSUE #961: SumDecimal always returns nullable=true
### Describe the bug

SumDecimal currently hardcodes nullable=true, and this is correct when ANSI mode is not enabled, because overflows cause null values. However, in ANSI mode, overflows cause exceptions. If the input is non-nullable then SumDecimal should probably also be non-nullable. The same is true for AvgDecimal.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vaibhawvipul**
## Which issue does this PR close?

Closes #961 .

## Rationale for this change

SumDecimal and AvgDecimal hardcode `nullable=true`. In Spark, `Sum.nullable` and `Average.nullable` both return true irrespective of ANSI mode. This PR documents that behavior and adds test coverage to ensure Comet stays consistent with Spark.

## What changes are included in this PR?

- Added comments to `SumDecimal.is_nullable()` and `AvgDecimal.is_nullable()` documenting that Spark always returns `true` for nullable, regardless of ANSI mode.
- Added an explicit `is_nullable()` override to `AvgDecimal` (previously relied on default) with the same documentation.

## How are these changes tested?

Added a test in `CometAggregateSuite` that exercises SUM and AVG on decimal columns with both nullable and non-nullable inputs, under both ANSI and non-ANSI modes. The test asserts `nullable == true` in all cases and uses `checkSparkAnswerAndOperator` to verify results match Spark.

### CODE REVIEW

File: native/spark-expr/src/agg_funcs/avg_decimal.rs [hunk 1]
```diff
@@ -207,6 +213,17 @@ impl AggregateUDFImpl for AvgDecimal {
     fn return_type(&self, arg_types: &[DataType]) -> Result<DataType> {
         avg_return_type(self.name(), &arg_types[0])
     }
+
+    fn is_nullable(&self) -> bool {
```
Comment (parthchandra) [inline native/spark-expr/src/agg_funcs/avg_decimal.rs:211]: In Spark, `Sum.nullable` and Average.nullable` both return `true` irrespective of Ansi mode.

File: spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala [hunk 2]
```diff
@@ -1917,6 +1917,43 @@ class CometAggregateSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
+        }
+
+        // Test SUM/AVG with nullable input
+        withParquetTable(nullableData, "tbl") {
+          val sumRes = sql("SELECT _2, sum(_1) FROM tbl GROUP BY _2")
+          checkSparkAnswerAndOperator(sumRes)
+
+          val avgRes = sql("SELECT _2, avg(_1) FROM tbl GROUP BY _2")
+          checkSparkAnswerAndOperator(avgRes)
+        }
```
Comment (parthchandra) [inline spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala:1954]: We can add an additional check to ensure that the nullability is compatible with Spark, for example :
`assert(sumRes.schema.fields(1).nullable == true)`

Comment (vaibhawvipul) [reply spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala:1954]: Added this test.

File: native/spark-expr/src/agg_funcs/avg_decimal.rs (hunk 1 above)
Comment (vaibhawvipul) [reply native/spark-expr/src/agg_funcs/avg_decimal.rs:211]: removed the ANSI behaviour to match spark behaviour.

**Comment by vaibhawvipul** [comment]
@parthchandra I have added a test in `CometAggregateSuite` to ensure that our behviour matches with spark, under both modes for nullability behaviour. 

I have reverted my changes in the rust code to keep comet's behaviour consistent with spark.

**Comment by parthchandra** [comment]
rebasing on main should fix the `check-missing-suites` ci failure

**Comment by vaibhawvipul** [comment]
> rebasing on main should fix the `check-missing-suites` ci failure

@parthchandra thank you for the approval. I think this can be merged.

**Comment by vaibhawvipul** [comment]
@parthchandra thank you for re-basing. i missed it.

**Comment by parthchandra** [comment]
Merged. Thanks @vaibhawvipul
