### PR TITLE
fix: Normalize s3 paths for PME key retriever

### LINKED ISSUE #2871: Parquet Encryption fails due to path mismatch (s3a:// vs s3://) in CometFileKeyUnwrapper cache
### Describe the bug

hen using Comet with Parquet Modular Encryption on an S3-compatible filesystem (like S3A), the query fails with a ParquetCryptoRuntimeException: Failed to find DecryptionKeyRetriever.

This is caused by a path string mismatch used as the key for the retrieverCache in CometFileKeyUnwrapper.java.

### Steps to reproduce

Configure a Spark job with Comet enabled to read encrypted Parquet files from an S3A path.
Enable Parquet Modular Encryption using the following configurations, which rely on Comet's JNI bridge to Parquet's native crypto framework:
parquet.crypto.factory.class=org.apache.parquet.crypto.keytools.PropertiesDrivenCryptoFactory
parquet.encryption.kms.client.class=<My KmsClient implementation>
Run a query that reads the encrypted data.

The job fails with the following exception stack trace:
Caused by: org.apache.comet.CometNativeException: Parquet error: Java exception during key retrieval: 
org.apache.parquet.crypto.ParquetCryptoRuntimeException: Failed to find DecryptionKeyRetriever for path: s3://user1-bucket/pme/...
	at org.apache.comet.parquet.Native.readNextRecordBatch(Native Method)
    ...

By adding debug logs to CometFileKeyUnwrapper.java, I was able to confirm the root cause.

The storeDecryptionKeyRetriever method is called by the native (Rust) side with a file path that includes the s3a:// scheme. The DecryptionKeyRetriever is then cached with this full path as the key.

-- Log from storeDecryptionKeyRetriever:
Creating new DecryptionKeyRetriever for path: s3a://user1-bucket/pme/.../file.parquet
Later, when the getKey method is called via JNI to retrieve the decryption key, the file path argument has been changed to use the s3:// scheme.

-- Log from getKey:
Getting key for path: s3://user1-bucket/pme/.../file.parquet
Since "s3a://..." and "s3://..." are different strings, the retrieverCache.get() call returns null, leading to the Failed to find DecryptionKeyRetriever exception. This indicates an inconsistency in how the file path is sourced or represented between the two JNI calls from the native side.

The issue can be resolved by normalizing the file path before using it as a key in both storeDecryptionKeyRetriever and getKey methods. A robust way to do this is to extract only the path component from the URI.

Here is a proposed change for CometFileKeyUnwrapper.java:

[CometFileKeyUnwrapper.java](https://github.com/user-attachments/files/24067596/CometFileKeyUnwrapper.java)

This normalization ensures that regardless of the scheme (s3a:// or s3://) passed from the native side, the cache lookup will be consistent and successful.

Thank you for looking into this!

### Expected behavior

_No response_

### Additional context

The Spark job should execute successfully, correctly decrypting the Parquet file data using the provided KMS client.

Specifically, inside CometFileKeyUnwrapper.java:

The retrieverCache.get(filePath) call within the getKey method should successfully find the DecryptionKeyRetriever instance that was previously stored by the storeDecryptionKeyRetriever method.
The cache lookup should be successful regardless of minor variations in the file path URI scheme (e.g., s3a:// vs. s3://) between the two JNI calls.
The job should not throw a ParquetCryptoRuntimeException and should proceed to read and process the decrypted data.

### PR DESCRIPTION
**Pull request by mbutrovich**
## Which issue does this PR close?

Closes #2871.

## What changes are included in this PR?

Normalize s3 paths in the key retriever cache.

## How are these changes tested?

Added a test that fails on main `native_datafusion` Parquet reader. With this change, the test passes.

### CODE REVIEW

File: common/src/main/java/org/apache/comet/parquet/CometFileKeyUnwrapper.java [hunk 1]
```diff
@@ -101,13 +101,33 @@ public class CometFileKeyUnwrapper {
...
+   * @return The file path with normalized S3 scheme (s3a://)
+   */
+  private String normalizeS3Scheme(final String filePath) {
+    // Normalize s3:// and s3n:// to s3a:// for consistent cache lookups
+    // This handles the case where ObjectStoreUrl uses s3:// but Spark uses s3a://
+    if (filePath.startsWith("s3://")) {
+      return "s3a://" + filePath.substring(5);
+    } else if (filePath.startsWith("s3n://")) {
+      return "s3a://" + filePath.substring(6);
+    }
```
Comment (andygrove) [inline common/src/main/java/org/apache/comet/parquet/CometFileKeyUnwrapper.java]: nit: rather than hard-code the lengths, I wonder if this would be clearer:

```suggestion
    String s3Prefix = "s3://";
    String s3nPrefix = "s3n://";
    if (filePath.startsWith(s3Prefix)) {
      return "s3a://" + filePath.substring(s3Prefix.length());
    } else if (filePath.startsWith(s3nPrefix)) {
      return "s3a://" + filePath.substring(s3nPrefix.length());
    }
```

File: spark/src/test/scala/org/apache/comet/parquet/ParquetReadFromS3Suite.scala [hunk 2]
```diff
@@ -76,4 +91,32 @@ class ParquetReadFromS3Suite extends CometS3TestBase with AdaptiveSparkPlanHelpe
     assertCometScan(df)
     assert(df.first().getLong(0) == 499500)
   }
+
+  test("write and read encrypted parquet from S3") {
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/comet/parquet/ParquetReadFromS3Suite.scala:95]: I don't know if this test exercises the changes to normalizing the path or not, but the test looks good

**Review by andygrove — APPROVED** [review]
Thanks @mbutrovich

File: spark/src/test/scala/org/apache/comet/parquet/ParquetReadFromS3Suite.scala (hunk 2 above)
Comment (mbutrovich) [reply spark/src/test/scala/org/apache/comet/parquet/ParquetReadFromS3Suite.scala:95]: It did fail on main, FWIW.
