### PR TITLE
fix: Native_datafusion reports correct files and bytes scanned

### LINKED ISSUE #3791: `native_datafusion` reports twice more files and bytes scanned
### Describe the bug

```
spark.range(10000000).repartition(20).write.parquet(location) 
spark.read.parquet("location").show(false)
```

Image

Image

which are twice more than original. The issue seems to be for metric only, the actual file read only once

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 0lai0**
## Which issue does this PR close?

Closes #3791 

## Rationale for this change

In `CometScanExec`, calling `getFilePartitions()` unconditionally executes `sendDriverMetrics()`. Because `getFilePartitions()` can be evaluated multiple times during planning (e.g., converting to `CometNativeScanExec`) and execution (e.g., fetching partitions), the `SQLMetric` accumulators like `numFiles` and `filesSize` were being duplicated. This led to incorrect double-counted values rendering in the Spark UI.

## What changes are included in this PR?

* Replaced `metrics(...).add()` with `metrics(...).set()` in `CometScanExec` to ensure idempotency when reporting metrics. 
* Wrapped the driver metric updates and Spark listener event dispatching inside a `lazy val`. This prevents both double-counting during Catalyst transformations (`makeCopy`) and sending redundant UI events.

## How are these changes tested?

* Added a dedicated end-to-end unit test in `CometExecSuite`.
* The test writes a dummy Parquet dataset, sequentially triggers multiple UI actions (`count` and `collect`) to force severe plan evaluations, and strictly asserts that `numFiles` is exactly `2` without any duplication.

### CODE REVIEW

File: spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala [hunk 1]
```diff
@@ -2173,6 +2173,38 @@ class CometExecSuite extends CometTestBase {
     }
   }
 
+  test("Native_datafusion reports correct files and bytes scanned") {
+    withTempDir { dir =>
+      val path = new java.io.File(dir, "test_metrics").getAbsolutePath
+      spark.range(100).repartition(2).write.mode("overwrite").parquet(path)
+
+      withSQLConf(
+        CometConf.COMET_ENABLED.key -> "true",
```
Comment (comphead) [inline spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala:2182]: Please include ` --conf spark.comet.scan.impl=native_datafusion`

**Comment by 0lai0** [comment]
Thank you all for the feedback. I’ll investigate this matter and fix it.

**Comment by mbutrovich** [comment]
Marking this as draft so we don't accidentally merge it, feel free to flip it back when it's ready for another look. Thanks @0lai0!

**Comment by 0lai0** [comment]
Thanks @mbutrovich . I'm still investigating the issue and trying to reproduce the scenario, but I haven't identified the root cause yet.

**Comment by 0lai0** [comment]
Thank you all for the review.
I've updated the test to strictly use `spark.comet.scan.impl=native_datafusion` as requested.

After checking further, I've simplified the fix by changing `metrics.add` to `metrics.set`. This ensures idempotency: if Catalyst evaluates the metric multiple times, it updates to the same fixed value rather than accumulating (which would cause double-counting) or resetting to zero.

**Comment by 0lai0** [comment]
This is the show on UI.
```
spark.range(10000000).repartition(20).write.parquet(location) 
spark.read.parquet("location").show(false)
```
But I'm not sure whether it is the correct snapshot.

Screenshot 2026-04-02 at 5 14 46 PM

File: spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala (hunk 1 above)
Comment (0lai0) [reply spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala:2182]: Thanks @comphead for review. I added this to the latest commit.

**Comment by comphead** [comment]
Checking, btw output_rows looks already also fixed in https://github.com/apache/datafusion-comet/pull/3842

testing num Files

File: spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala [hunk 2]
```diff
@@ -2173,6 +2173,39 @@ class CometExecSuite extends CometTestBase {
     }
   }
 
+  test("Native_datafusion reports correct files and bytes scanned") {
+    withTempDir { dir =>
```
Comment (comphead) [inline spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala:2177]:
```suggestion
    val inputFiles = 2
    withTempDir { dir =>
```

File: spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala [hunk 3]
```diff
@@ -2173,6 +2173,39 @@ class CometExecSuite extends CometTestBase {
...
+      val path = new java.io.File(dir, "test_metrics").getAbsolutePath
+      spark.range(100).repartition(2).write.mode("overwrite").parquet(path)
```
Comment (comphead) [inline spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala:2179]:
```suggestion
      spark.range(100).repartition(inputFiles).write.mode("overwrite").parquet(path)
```

File: spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala [hunk 4]
```diff
@@ -2173,6 +2173,39 @@ class CometExecSuite extends CometTestBase {
...
+            case n: org.apache.spark.sql.comet.CometScanExec => n
+          }
+          .getOrElse {
+            fail(
+              s"Comet scan node not found in the physical plan. Plan: \n${df.queryExecution.executedPlan}")
+          }
+
+        val numFiles = scanNode.metrics("numFiles").value
+        assert(
+          numFiles == 2,
```
Comment (comphead) [inline spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala:2203]:
```suggestion
          numFiles == inputFiles,
```

File: spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala [hunk 5]
```diff
@@ -2173,6 +2173,39 @@ class CometExecSuite extends CometTestBase {
...
+          s"Expected exactly 2 files to be scanned, but got metrics reporting $numFiles")
```
Comment (comphead) [inline spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala:2204]:
```suggestion
          s"Expected exactly $inputFiles files to be scanned, but got metrics reporting $numFiles")
```

**Comment by comphead** [comment]
I went ahead with the merge to test it sooner

**Comment by 0lai0** [comment]
Hi @comphead , apologies for the late reply! Thanks for taking care of the merge to test it sooner. I'll open a quick follow-up PR shortly to polish the test as you suggested.
