### PR TITLE
fix: Iceberg reflection for current() on TableOperations hierarchy

### LINKED ISSUE #3894: `NoSuchMethodException` when reflecting Iceberg TableOperations.current()
### Describe the bug

Comet's Iceberg reflection path calls `table.operations().current()`.
The current implementation uses `getDeclaredMethod("current")` on the concrete `operations` runtime class. 
Some implementations (e.g. Hive/Glue style), `current()` is declared on  superclass (`BaseMetastoreTableOperations`), not on the subclass itself.
This can throw `NoSuchMethodException`.

### Steps to reproduce

Query an Iceberg table backd by Hive Catalog

### Expected behavior

`current()` should be resolved by walking the class hierarchy , so inherited methods are found correctly.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by karuppayya**
## Which issue does this PR close?

Closes #3894.

## Rationale for this change

Fix `NoSuchMethodException` from Iceberg Reflection  

## What changes are included in this PR?
Use `findMethodInHierarchy` instead of `getDeclaredMethod` so getTableMetadata and format-version reflection work when `current()` is declared on a superclass (e.g. BaseMetastoreTableOperations for Hive/Glue-style ops).

## How are these changes tested?

- Added Units
- Tested by querying Hive backed Iceberg tables where this issue is present.

### CODE REVIEW

**Comment by karuppayya** [comment]
cc:  @andygrove @mbutrovich @parthchandra 
can any of you help review?
Also looks like workflow needs maintainer approval to progress(But remember that it used to work without this)

File: spark/src/main/scala/org/apache/comet/iceberg/IcebergReflection.scala [hunk 1]
```diff
@@ -228,11 +228,18 @@ object IcebergReflection extends Logging {
           val opsMethod = table.getClass.getDeclaredMethod("operations")
           opsMethod.setAccessible(true)
           val ops = opsMethod.invoke(table)
-          val currentMethod = ops.getClass.getDeclaredMethod("current")
-          currentMethod.setAccessible(true)
-          val metadata = currentMethod.invoke(ops)
-          val formatVersionMethod = metadata.getClass.getMethod("formatVersion")
-          Some(formatVersionMethod.invoke(metadata).asInstanceOf[Int])
+          findMethodInHierarchy(ops.getClass, "current")
```
Comment (parthchandra) [inline spark/src/main/scala/org/apache/comet/iceberg/IcebergReflection.scala:231]: Is current the only method affected? `operations` (a few lines above this) is calling `getDeclaredMethod` also. 
Also, are there other catalog implementations that could have similar issues but for other methods?

Comment (karuppayya) [reply spark/src/main/scala/org/apache/comet/iceberg/IcebergReflection.scala:231]: I think we could always call replace all occurences of `getDeclaredMethod` with `findMethodInHierarchy`
Especially, those that assume the superclass's depth seems fragile
```
      val tasksMethod = scan.getClass.getSuperclass
        .getDeclaredMethod("tasks")
```
```
      val filterExpressionsMethod = scan.getClass.getSuperclass.getSuperclass
        .getDeclaredMethod("filterExpressions")
 ```

Comment (parthchandra) [reply spark/src/main/scala/org/apache/comet/iceberg/IcebergReflection.scala:231]: @mbutrovich wdyt? Is there a potential performance impact here if we replace `getDeclaredMethod` with `findMethodInHierarchy`?

Comment (mbutrovich) [reply spark/src/main/scala/org/apache/comet/iceberg/IcebergReflection.scala:231]: I think I tried that at some point but it's been at least 6 months, open to trying again.

Comment (parthchandra) [reply spark/src/main/scala/org/apache/comet/iceberg/IcebergReflection.scala:231]: Thinking this over, I feel we can defer changing everything over to use `findMethodInHierarchy` until we hit an issue.

**Review by parthchandra — APPROVED** [review]
lgtm, pending ci

File: spark/src/main/scala/org/apache/comet/iceberg/IcebergReflection.scala (hunk 1 above)
Comment (karuppayya) [reply spark/src/main/scala/org/apache/comet/iceberg/IcebergReflection.scala:231]: Sgtm

**Comment by parthchandra** [comment]
We've exposed a latent bug, perhaps. In `CometScanRule.validateIcebergFileScanTasks`, `uri.getScheme` returns `null` for the relative paths returned by `InMemoryCatalog`. We check 
```
        if (scheme != null && !supportedSchemes.contains(scheme)) {
          unsupportedSchemes += scheme
        }
 ```
 which allows such paths and this later fails. 
 @mbutrovich, any thoughts on how to handle this?

**Comment by karuppayya** [comment]
@mbutrovich ping!

**Comment by mbutrovich** [comment]
Thanks for improving the Iceberg support, @karuppayya! I took a look at this today:

The `findMethodInHierarchy` fix is correct, but it widens the set of scans Comet intercepts. Previously, `getDeclaredMethod("current")` failed for `InMemoryCatalog`'s operations class (where `current()` is inherited), causing fallback to Spark. Now the reflection succeeds and Comet runs the scan natively.

The Iceberg CI failures (`TestSparkReaderDeletes`) happen because Comet's native reader (iceberg-rust/arrow-rs) doesn't expose the `number of row deletes applied` metric that these tests assert on. That metric is an Iceberg Java reader concept.

The root cause is `CometScanRule.validateIcebergFileScanTasks` line 809:

```scala
if (scheme != null && !supportedSchemes.contains(scheme))
```

`InMemoryCatalog` returns relative paths where `URI.getScheme` is `null`. The null check lets them through. Fix: treat null scheme as unsupported so these scans fall back.

```scala
if (scheme == null || !supportedSchemes.contains(scheme))
```

Same fix needed for the delete file scheme check on line 851.

**Comment by mbutrovich** [comment]
I’ll keep kicking CI :)

**Comment by karuppayya** [comment]
> Fix: treat null scheme as unsupported so these scans fall back.

Rejecting scheme == null also blocks HadoopCatalog local paths (e.g. /tmp/warehouse/...) which have no URI scheme — this caused all CometIcebergNativeSuite tests to fail again. 

Instead, added an explicit FileIO type check. (REST catalogs are unaffected(mentioned in the code comment) since the client-side table uses ResolvingFileIO, not InMemoryFileIO (see [RESTSessionCatalog.DEFAULT_FILE_IO_IMPL](https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java#L117)))

Also added `countDeletes() = false` override in the Iceberg  diffs for 3.5 (present already for 3.5) since iceberg-rust doesn't expose the delete count metric.

**Review by mbutrovich — APPROVED** [review]
I have minor style nits but don't want to send you through CI again. Thanks @karuppayya!
