### PR TITLE
fix: share unified memory pools across native execution contexts within a task

### LINKED ISSUE #3921: task memory limit is not shared across all plans for the same task
### Describe the bug

In CometExecIterator, `memoryLimitPerTask` is passed into `executePlan`. However, `executePlan` is sometimes recursive, such as when native shuffle plan reads from another native plan via `CometBatchIterator` and another `CometExecIterator` instance for the same task.

This results in the memory pools being given more memory than is available.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by andygrove**
## Which issue does this PR close?

Closes #3921

## Rationale for this change

When Comet executes a shuffle, it creates two native execution contexts that run concurrently within the same Spark task (e.g. one for pre-shuffle operators and one for the shuffle writer). Previously, each context created its own memory pool with the full per-task memory limit, effectively allowing 2x the intended memory to be consumed. This is a performance bug — not a correctness issue — but it causes significantly higher memory usage than expected, leading to OOM errors that can only be worked around by over-provisioning memory.

## What changes are included in this PR?

- Make `fair_unified` and `greedy_unified` memory pools task-shared, so a single pool instance is reused across all native execution contexts within the same Spark task. This uses the same `TASK_SHARED_MEMORY_POOLS` mechanism that the on-heap `greedy_task_shared` and `fair_spill_task_shared` pools already use.
- Fix a tracing bug where `total_reserved_for_thread()` and `unregister_and_total()` double-counted memory when multiple execution contexts shared the same pool `Arc`. Deduplicates by `Arc` data pointer before summing `reserved()`.
- Update tuning guide to document that both pool types are shared across execution contexts.

No new configuration options are added. The existing `fair_unified` (default) and `greedy_unified` pool names are unchanged. No functional change — queries produce the same results, but memory usage is now correctly bounded.

## How are these changes tested?

With this change I was able to run TPC-H and TPC-DS @ 1TB with just 8GB off-heap memory. Previously I was seeing OOM at 16 GB.

### CODE REVIEW

File: common/src/main/scala/org/apache/comet/CometConf.scala [hunk 1]
```diff
@@ -647,10 +647,14 @@ object CometConf extends ShimCometConf {
       .category(CATEGORY_TUNING)
       .doc(
         "The type of memory pool to be used for Comet native execution when running Spark in " +
-          "off-heap mode. Available pool types are `greedy_unified` and `fair_unified`. " +
+          "off-heap mode. Available pool types are `greedy_unified`, `fair_unified`, and " +
+          "`fair_unified_task_shared`. The `fair_unified_task_shared` pool is shared across " +
```
Comment (comphead) [inline common/src/main/scala/org/apache/comet/CometConf.scala]: read the description twice, it is difficult to understand without example what exactly `fair_unified_task_shared` helps to achieve

File: docs/source/user-guide/latest/tuning.md [hunk 2]
```diff
@@ -56,15 +56,29 @@ For more details about Spark off-heap memory mode, please refer to [Spark docume
 
 Comet implements multiple memory pool implementations. The type of pool can be specified with `spark.comet.exec.memoryPool`.
 
+When Comet executes a shuffle, it creates two separate native plans within the same Spark task: the child plan
```
Comment (comphead) [inline docs/source/user-guide/latest/tuning.md]: maybe it is not a plan, and rather a stage DAG? 

plan is per operator: scan-> shuffle -> write
stage DAG is different, the plan above split into
Stage1: scan + shuffle write
Stage2: shuffle read  + write

File: native/core/src/execution/jni_api.rs [hunk 3]
```diff
@@ -141,15 +141,29 @@ fn unregister_and_total(thread_id: u64, context_id: i64) -> usize {
             map.remove(&thread_id);
             return 0;
         }
-        return pools.values().map(|p| p.reserved()).sum::<usize>();
+        let mut seen = std::collections::HashSet::new();
+        return pools
+            .values()
+            .filter(|p| seen.insert(Arc::as_ptr(p) as *const () as usize))
+            .map(|p| p.reserved())
+            .sum::<usize>();
```
Comment (comphead) [inline native/core/src/execution/jni_api.rs:153]:
```suggestion
return pools
    .values()
    .filter_map(|p| {
        let ptr = Arc::as_ptr(p) as *const ();
        seen.insert(ptr).then(|| p.reserved())
    })
```

File: native/core/src/execution/jni_api.rs [hunk 4]
```diff
@@ -141,15 +141,29 @@ fn unregister_and_total(thread_id: u64, context_id: i64) -> usize {
...
     let map = get_thread_memory_pools().lock();
     map.get(&thread_id)
-        .map(|pools| pools.values().map(|p| p.reserved()).sum::<usize>())
+        .map(|pools| {
+            // Deduplicate pools that share the same underlying allocation
+            // (e.g. task-shared pools registered by multiple execution contexts)
+            let mut seen = std::collections::HashSet::new();
+            pools
+                .values()
+                .filter(|p| seen.insert(Arc::as_ptr(p) as *const () as usize))
```
Comment (comphead) [inline native/core/src/execution/jni_api.rs]: same

File: common/src/main/scala/org/apache/comet/CometConf.scala (hunk 1 above)
Comment (andygrove) [reply common/src/main/scala/org/apache/comet/CometConf.scala]: Updated. Let me know if this is clearer now.

File: docs/source/user-guide/latest/tuning.md (hunk 2 above)
Comment (andygrove) [reply docs/source/user-guide/latest/tuning.md]: It is really DataFusion execution contexts. I updated.

File: native/core/src/execution/jni_api.rs [hunk 5]
```diff
@@ -141,15 +141,33 @@ fn unregister_and_total(thread_id: u64, context_id: i64) -> usize {
             map.remove(&thread_id);
             return 0;
         }
-        return pools.values().map(|p| p.reserved()).sum::<usize>();
+        let mut seen = std::collections::HashSet::new();
```
Comment (mbutrovich) [inline native/core/src/execution/jni_api.rs]: Claude loves these fully qualified types. Do we need it?

File: native/core/src/execution/jni_api.rs [hunk 6]
```diff
@@ -141,15 +141,33 @@ fn unregister_and_total(thread_id: u64, context_id: i64) -> usize {
...
+            .filter_map(|p| {
+                let ptr = Arc::as_ptr(p) as *const ();
+                seen.insert(ptr).then(|| p.reserved())
+            })
+            .sum::<usize>();
     }
     0
 }
 
 fn total_reserved_for_thread(thread_id: u64) -> usize {
```
Comment (mbutrovich) [inline native/core/src/execution/jni_api.rs:158]: This is only used for tracing, right?

**Review by mbutrovich — APPROVED** [review]
Minor nits, thanks @andygrove!

File: native/core/src/execution/jni_api.rs (hunk 6 above)
Comment (andygrove) [reply native/core/src/execution/jni_api.rs:158]: Yes

File: native/core/src/execution/jni_api.rs (hunk 5 above)
Comment (andygrove) [reply native/core/src/execution/jni_api.rs]: Fixed. Thanks.

**Comment by andygrove** [comment]
Thanks for the reviews @comphead @mbutrovich
