### PR TITLE
fix: incorrect result on Comet multiple column distinct count

### LINKED ISSUE #267: Different behavior of distinct count on null inputs
### Describe the bug

A few Spark tests with distinct count failed while working on #250: https://github.com/apache/arrow-datafusion-comet/actions/runs/8681807652/job/23805034669?pr=250

```
[info] TwoLevelAggregateHashMapSuite:
[info] - multiple column distinct count *** FAILED *** (530 milliseconds)
[info]   Results do not match for query:
...
[info]   == Results ==
[info]   !== Correct Answer - 1 ==   == Spark Answer - 1 ==
[info]   !struct<>                   struct<count(key1, key2, key3):bigint>
[info]   ![3]                        [4] (QueryTest.scala:243)
```

Spark distinct count aggregation doesn't count null inputs. I.e.,

```scala
override lazy val updateExpressions = {
  ..
  Seq(
    /* count = */ If(nullableChildren.map(IsNull).reduce(Or), count, count + 1L)
  )
}
```

But seems DataFusion `count` aggregation function behaves differently.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #267.

### CODE REVIEW

File: core/src/execution/datafusion/planner.rs [hunk 1]
```diff
@@ -1094,8 +1094,15 @@ impl PhysicalPlanner {
...
-                Ok(Arc::new(Count::new(child, "count", DataType::Int64)))
+                let mut children = vec![];
+                for child in expr.children.iter() {
+                    children.push(self.create_expr(child, schema.clone())?);
+                }
+                Ok(Arc::new(Count::new_with_multiple_exprs(
+                    children,
+                    "count",
+                    DataType::Int64,
+                )))
```
Comment (viirya) [inline core/src/execution/datafusion/planner.rs:1105]: `Count` could take multiple children, but we used one child only.

**Comment by viirya** [comment]
cc @huaxingao @sunchao

**Comment by viirya** [comment]
cc @andygrove

File: core/src/execution/datafusion/planner.rs [hunk 2]
```diff
@@ -1094,8 +1094,15 @@ impl PhysicalPlanner {
     ) -> Result<Arc<dyn AggregateExpr>, ExecutionError> {
         match spark_expr.expr_struct.as_ref().unwrap() {
             AggExprStruct::Count(expr) => {
-                let child = self.create_expr(&expr.children[0], schema)?;
-                Ok(Arc::new(Count::new(child, "count", DataType::Int64)))
+                let mut children = vec![];
+                for child in expr.children.iter() {
+                    children.push(self.create_expr(child, schema.clone())?);
+                }
```
Comment (andygrove) [inline core/src/execution/datafusion/planner.rs:1100]: This could be written in a functional style to avoid mutating state.

```suggestion
                let children = expr
                    .children
                    .iter()
                    .map(|child| self.create_expr(child, schema.clone()))
                    .collect::<Result<Vec<_>, _>>()?;
```

**Review by andygrove — APPROVED** [review]

**Comment by viirya** [comment]
Merged. Thanks.
