### PR TITLE
fix: make shuffle fallback decisions sticky across planning passes

### LINKED ISSUE #3870: DPP fallback not working correct in awslabs TPC-DS benchmark
### Describe the bug

In the awslabs benchmark, some scans in q25 fell back to Spark because the scans use DPP. This is expected behavior. However, the fallback somehow changed the Spark plan, removing DPP, causing the scan to read all partitions, resulting in dramatic regression.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### LINKED ISSUE #3949: [INTERNAL_ERROR] The "collect" action failed.
### Describe the bug

awslabs ran into the following error when testing a recent 0.15.0 snapshot release (`0.15.0-preview-1` tag). For some reason, there is no more detail provided in the stack trace, making this difficult to debug.

```
Execution 'q14b-v4.0' failed: [INTERNAL_ERROR] The "collect" action failed. You hit a bug in Spark or the Spark plugins you use. Please, report this bug to the corresponding communities or vendors, and provide the full stack trace.:
org.apache.spark.SparkException$.internalError(SparkException.scala:107)
org.apache.spark.sql.execution.QueryExecution$.toInternalError(QueryExecution.scala:536)
org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:548)
org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:4321)
org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
org.apache.spark.sql.Dataset.withAction(Dataset.scala:4321)
org.apache.spark.sql.Dataset.collect(Dataset.scala:3575)
```

This issue only happens on specific queries in TPC-DS:

```
q14a-v4.0
q14b-v4.0
q31-v4.0
q47-v4.0
q57-v4.0
```

The issue does not happen with 0.14.0 release.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

```scala
/**
   * Converts asserts, null pointer exceptions to internal errors.
   */
  private[sql] def toInternalError(msg: String, e: Throwable): Throwable = e match {
    case e @ (_: java.lang.NullPointerException | _: java.lang.AssertionError) =>
      SparkException.internalError(
        msg + " You hit a bug in Spark or the Spark plugins you use. Please, report this bug " +
          "to the corresponding communities or vendors, and provide the full stack trace.",
        e)
    case e: Throwable =>
      e
  }
```

### PR DESCRIPTION
**Pull request by andygrove**
## Which issue does this PR close?

Closes #3949
Closes https://github.com/apache/datafusion-comet/issues/3870

There is a follow on issue https://github.com/apache/datafusion-comet/issues/3984 to clean this up. This was implemented quite hastily.

## Rationale for this change

Comet's shuffle-support predicates (`nativeShuffleSupported`, `columnarShuffleSupported` in `CometShuffleExchangeExec`) are called at both initial planning and AQE stage-prep. Some fallback decisions depend on the surrounding plan shape — for example, the presence of a DPP scan below a shuffle. Between the two passes, AQE wraps already-materialized child stages in `ShuffleQueryStageExec`, a `LeafExecNode` whose `children` is `Seq.empty`, so a naive re-evaluation can flip the decision.

Concrete mechanism (the trigger for #3949): `stageContainsDPPScan` walks `s.child.exists(...)` looking for a `FileSourceScanExec` with a `PlanExpression` partition filter. When the DPP subtree sits under a materialized `ShuffleQueryStageExec`, `.exists` stops at the wrapper and the DPP scan becomes invisible. The same shuffle that correctly fell back to Spark at initial planning is converted to Comet at stage prep. The resulting plan has a `CometColumnarExchange` above a materialized row-mode stage whose subtree still contains a Spark-fallback DPP scan — a boundary that breaks during `BroadcastExchangeExec.doCanonicalize` with `AssertionError` at `ColumnarToRowExec.<init>(Columnar.scala:70)` (because `child.supportsColumnar` is false after canonicalization).

## What changes are included in this PR?

- New `CometFallback` object with `markForFallback` / `isMarkedForFallback`. Distinct from `CometExplainInfo.EXTENSION_INFO` on purpose: the explain tag accumulates informational reasons (including rolled-up child reasons) and treating any presence as a fallback signal is too coarse — it breaks legitimate conversions (e.g. a shuffle tagged "Comet native shuffle not enabled" should still be eligible for columnar shuffle). The fallback tag exists only for decisions that must remain sticky.
- `nativeShuffleSupported` and `columnarShuffleSupported` short-circuit on `isMarkedForFallback(s)` at the top.
- The DPP branch of `columnarShuffleSupported` now uses `markForFallback` instead of `withInfo`, so the decision persists across AQE replanning.

Design rule (worth noting for future contributors): `markForFallback` must only be used for decisions that mean the whole stage falls back regardless of shuffle mode (DPP qualifies). Per-mode reasons — e.g. "unsupported data type for native only" — must keep using `withInfo`, because the native check runs before the columnar check and a sticky marker set in native would prevent columnar from getting a shot.

## How are these changes tested?

Two new test suites:

1. `CometShuffleFallbackStickinessSuite` — unit-level invariant:
   - Marked shuffle: both `nativeShuffleSupported` and `columnarShuffleSupported` return `false`.
   - Negative case: explain info alone (e.g. "Comet native shuffle not enabled") must **not** imply the sticky marker.
   - End-to-end-on-one-shuffle: plan a real DPP query, run the support check once to set the marker, swap the shuffle's child for an opaque `LeafExecNode` that hides the DPP subtree (mimicking a materialized stage), and assert the second call still returns `false`.

2. `CometDppFallbackRepro3949Suite` — end-to-end reproduction of the crash:
   - `mechanism`: builds a real DPP plan and asserts the sticky marker survives an AQE-style child wrap (`withNewChildren` preserves tree-node tags).
   - `end-to-end`: runs five DPP-flavored queries across three AQE variants; captures any `collect()` failure and any Comet shuffle in the final plan whose subtree still contains a DPP scan.
     - **Verified on main** (without the fix): `q4` — a UNION ALL of three DPP-using subqueries with an outer rollup aggregate — crashes under `smj+aqe` and `smj+aqe+coalesce` with the exact #3949 stack trace (`AssertionError` through `ColumnarToRowExec.<init>(Columnar.scala:70)` during `BroadcastExchangeExec.doCanonicalize`).
     - **With this PR applied**: both suites pass.

Existing `DPP fallback` and `DPP fallback avoids inefficient Comet shuffle (#3874)` tests in `CometExecSuite` continue to pass.

### CODE REVIEW

File: spark/src/main/scala/org/apache/comet/CometFallback.scala [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+
+  val STAGE_FALLBACK_TAG: TreeNodeTag[Set[String]] =
+    new TreeNodeTag[Set[String]]("CometStageFallback")
+
+  /**
+   * Mark a node so that subsequent shuffle-support re-evaluations fall back to Spark without
+   * re-deriving the decision from the (possibly reshaped) subtree. Also records the reason in the
+   * usual explain channel so it surfaces in extended explain output.
+   */
+  def markForFallback[T <: TreeNode[_]](node: T, reason: String): T = {
```
Comment (parthchandra) [inline spark/src/main/scala/org/apache/comet/CometFallback.scala:57]: This is much better than using explain info

File: spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala [hunk 2]
```diff
@@ -450,12 +456,17 @@ object CometShuffleExchangeExec
...
+      return false
+    }
+
     if (!isCometShuffleEnabledWithInfo(s)) {
       return false
     }
 
     if (CometConf.COMET_DPP_FALLBACK_ENABLED.get() && stageContainsDPPScan(s)) {
-      withInfo(s, "Stage contains a scan with Dynamic Partition Pruning")
+      markForFallback(s, "Stage contains a scan with Dynamic Partition Pruning")
```
Comment (parthchandra) [inline spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala:469]: Should we add the reason to explainInfo?

File: spark/src/test/scala/org/apache/spark/sql/comet/CometDppFallbackRepro3949Suite.scala [hunk 3]
```diff
@@ -0,0 +1,430 @@
...
+        val postAqeDecision = CometShuffleExchangeExec.columnarShuffleSupported(postAqeShuffle)
+
+        val postAqeDppVisible = postAqeShuffle.child.exists {
+          case scan: FileSourceScanExec =>
+            scan.partitionFilters.exists(_.exists(_.isInstanceOf[PlanExpression[_]]))
+          case _ => false
+        }
+
+        // scalastyle:off println
+        println("=== mechanism check ===")
```
Comment (parthchandra) [inline spark/src/test/scala/org/apache/spark/sql/comet/CometDppFallbackRepro3949Suite.scala]: Use `log` insted of `println`, or perhaps you meant to remove this?

**Review by parthchandra — APPROVED** [review]
lgtm. Some minor comments

File: spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala (hunk 2 above)
Comment (andygrove) [reply spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala:469]: `markForFallback` does call `withInfo` so we still get the explain info recorded

Comment (andygrove) [reply spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala:469]: having two approaches seems a bit hacky though. I filed follow on issue to clean this up. https://github.com/apache/datafusion-comet/issues/3984

File: spark/src/test/scala/org/apache/spark/sql/comet/CometDppFallbackRepro3949Suite.scala (hunk 3 above)
Comment (andygrove) [reply spark/src/test/scala/org/apache/spark/sql/comet/CometDppFallbackRepro3949Suite.scala]: I removed the debug println

**Comment by andygrove** [comment]
Merged. Thanks @parthchandra
