### PR TITLE
fix: add EmptySchemaShufflePartitioner and test from #3858

### LINKED ISSUE #3846: `native_datafusion` crashes for repartition + count
### Describe the bug

Valid query

```
spark.read.parquet("hdfs://location").repartition(50).count()
```

Crashes with

```
org.apache.comet.CometNativeException: External error: Execution error: Error in shuffle write: Arrow error: Invalid argument error: must either specify a row count or at least one column
```

### Steps to reproduce

_No response_

### Expected behavior

should work

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mbutrovich**
## Which issue does this PR close?

Closes #3846.

## Rationale for this change

Native shuffle above a native scan that does not project any columns (_e.g._, `COUNT(*)`) results in `RecordBatch`es with an empty schema but valid number of rows. Native shuffle currently panics trying to `interleave` those batches, but we can fast path this scenario with a special partitioner. It is similar to the `SinglePartitionShufflePartitioner` but instead of concatenating batches to write to a shuffle file for a single partition, it accumulates the number of rows, then writes a single IPC batch for the number of rows, but makes sure the index file has the expected number of partitions.

## What changes are included in this PR?

- `native/shuffle/src/partitioners/empty_schema.rs`: new `EmptySchemaShufflePartitioner` that accumulates row count, writes a single zero-column IPC batch to partition 0, and fills the index with equal offsets for all other partitions
- `native/shuffle/src/partitioners/mod.rs`: exports the new partitioner
- `native/shuffle/src/shuffle_writer.rs`: branches on `schema.fields().is_empty()` before falling through to `MultiPartitionShuffleRepartitioner`; added Rust test verifying row count roundtrip and index structure
- `spark/.../CometNativeShuffleSuite.scala`: integration test from PR #3858 for `repartition(10).count()` with native DataFusion scan

## How are these changes tested?

New test from #3858 that reflects repro in #3846.

### CODE REVIEW

**Comment by mbutrovich** [comment]
Based on grepping logs when I still has it at INFO level, these Spark SQL tests cover this codepath in addition to the unit test we added to CometNativeShuffleSuite:
1. `postgreSQL/union.sql`
2. `subquery/exists-subquery/exists-orderby-limit.sql `

File: native/shuffle/src/partitioners/empty_schema.rs [hunk 1]
```diff
@@ -0,0 +1,135 @@
...
+use datafusion::common::DataFusionError;
+use std::fs::OpenOptions;
+use std::io::{BufWriter, Seek, Write};
+use tokio::time::Instant;
+
+/// A partitioner for zero-column schemas (e.g. queries where ColumnPruning removes all columns).
+/// This handles shuffles for operations like COUNT(*) that produce empty-schema record batches
+/// but contain a valid row count. Accumulates the total row count and writes a single
+/// zero-column IPC batch to partition 0. All other partitions get empty entries in the index file.
+pub(crate) struct EmptySchemaShufflePartitioner {
```
Comment (comphead) [inline native/shuffle/src/partitioners/empty_schema.rs:32]: would be useful to attach a data flow graph or something, so can figure how data transforms across shuffle phases?

File: native/shuffle/src/partitioners/empty_schema.rs [hunk 2]
```diff
@@ -0,0 +1,135 @@
...
+            total_rows: 0,
+            metrics,
+        })
+    }
+}
+
+#[async_trait::async_trait]
+impl ShufflePartitioner for EmptySchemaShufflePartitioner {
+    async fn insert_batch(&mut self, batch: RecordBatch) -> datafusion::common::Result<()> {
+        let start_time = Instant::now();
```
Comment (comphead) [inline native/shuffle/src/partitioners/empty_schema.rs:71]: I'm starting to think if we need to wrap timings into macros and make them optional 🤔

File: native/shuffle/src/partitioners/empty_schema.rs [hunk 3]
```diff
@@ -0,0 +1,135 @@
...
+        // Write index file: partition 0 spans [0, data_file_length), all others are empty
+        let index_file = OpenOptions::new()
+            .write(true)
+            .create(true)
+            .truncate(true)
+            .open(&self.output_index_file)
+            .map_err(|e| DataFusionError::Execution(format!("shuffle write error: {e:?}")))?;
+        let mut index_writer = BufWriter::new(index_file);
+        index_writer.write_all(&0i64.to_le_bytes())?;
+        for _ in 0..self.num_output_partitions {
```
Comment (comphead) [inline native/shuffle/src/partitioners/empty_schema.rs:123]: `self.num_output_partitions` ? Am I right it should be just 1 parittion?

Comment (mbutrovich) [reply native/shuffle/src/partitioners/empty_schema.rs:123]: The shuffle writer must write index entries for all target partitions, even if we're accumulating everything into a single batch in the first partition.

File: native/shuffle/src/partitioners/empty_schema.rs (hunk 2 above)
Comment (mbutrovich) [reply native/shuffle/src/partitioners/empty_schema.rs:71]: Timers have cost, but in the grand scheme of Spark jobs that last hours or days, they're not the highest priority to optimize.

File: native/shuffle/src/partitioners/empty_schema.rs (hunk 1 above)
Comment (mbutrovich) [reply native/shuffle/src/partitioners/empty_schema.rs:32]: I'm not sure what you have in mind for this one because this partitioner targets a very narrow type of queries. I think there are other resources to read about general Spark shuffle behavior.

**Review by comphead — APPROVED** [review]
Thanks @mbutrovich lets go with this PR and get rid of shuffle crash!
