### PR TITLE
fix: Remove redundant data copy in columnar shuffle

### LINKED ISSUE #232: Remove redundant data copy in columnar shuffle
### Describe the bug

We observed that when using columnar shuffle, there are additional memory consumption which will cause out of memory errors on workloads like TPC-DS and TPC-H.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #232.

### CODE REVIEW

File: spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala [hunk 1]
```diff
@@ -208,6 +217,50 @@ object CometShuffleExchangeExec extends ShimCometShuffleExchangeExec {
...
+        //
+        // Exchange never configures its ShuffledRDDs with aggregators or key orderings, and the
+        // serializer in Spark SQL always satisfy the properties, so we only need to check whether
+        // the number of partitions exceeds the limitation.
+        false
+      } else {
+        // This different to Spark `SortShuffleManager`.
+        // Comet doesn't use Spark `ExternalSorter` to buffer records in memory, so we don't need to
+        // copy.
+        false
```
Comment (viirya) [inline spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala:256]: Basically Comet shuttle doesn't run through the ways that require additional copying on row objects like Spark. So these branches are returning `false` at all. But I keep them to make it clear to explain the reason.

**Comment by viirya** [comment]
cc @sunchao @parthchandra

File: spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala [hunk 2]
```diff
@@ -208,6 +216,50 @@ object CometShuffleExchangeExec extends ShimCometShuffleExchangeExec {
     dependency
   }
 
+  /**
+   * This is copied from Spark `ShuffleExchangeExec.needToCopyObjectsBeforeShuffle`. The only
+   * difference is that we use `BosonShuffleManager` instead of `SortShuffleManager`.
+   */
+  private def needToCopyObjectsBeforeShuffle(partitioner: Partitioner): Boolean = {
```
Comment (viirya) [inline spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala:223]: Spark `needToCopyObjectsBeforeShuffle` will return `true` if it finds the shuffle manager is not Spark `SortShuffleManager`. So it incurs additional row copying for all cases which are redundant for Comet and increase memory usage.

Comment (viirya) [reply spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala:223]: This could also improve the shuffle time on columnar shuffle as it removes expensive copying operation.

File: spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala [hunk 3]
```diff
@@ -219,21 +271,146 @@ object CometShuffleExchangeExec extends ShimCometShuffleExchangeExec {
       newPartitioning: Partitioning,
       serializer: Serializer,
       writeMetrics: Map[String, SQLMetric]): ShuffleDependency[Int, InternalRow, InternalRow] = {
-    val sparkShuffleDep = ShuffleExchangeExec.prepareShuffleDependency(
-      rdd,
-      outputAttributes,
-      newPartitioning,
-      serializer,
-      writeMetrics)
+    val part: Partitioner = newPartitioning match {
```
Comment (parthchandra) [inline spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala:274]: Is there a difference between this and calling `ShuffleExchangeExec.prepareShuffleDependency` directly?

File: spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala (hunk 2 above)
Comment (parthchandra) [reply spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala:223]: So not a memory leak, just double the memory usage?

Comment (viirya) [reply spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala:223]: Yea, I think so.

File: spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala (hunk 3 above)
Comment (viirya) [reply spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala:274]: We call `ShuffleExchangeExec.prepareShuffleDependency` before.

But now we need to overwrite `needToCopyObjectsBeforeShuffle` which is a private method in Spark. So we need to copy the code of `ShuffleExchangeExec.prepareShuffleDependency` here.

File: spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala (hunk 2 above)
Comment (singhpk234) [reply spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala:223]: [a bit orthogonal] how did you find it ? by profiling or by just analyzing the shuffle size, what was the scale of tpcds (3TB) curious ?

Comment (viirya) [reply spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala:223]: I did memory profiling when running TPCDS queries locally. Because it is local benchmark, the scale is small. This issue is not only for larger scale so it can be profiled in small scale too.

**Comment by viirya** [comment]
The failed test seems flaky? I ran it multiple times locally and got different results (Comet or Spark):

```
  !== Correct Answer - 6 ==   == Spark Answer - 6 ==
   struct<a:int>              struct<a:int>
   [6]                        [6]
  ![10]                       [9]
  ![9]                        [7]
  ![7]                        [8]
  ![8]                        [5]
  ![5]                        [10] (QueryTest.scala:243)


  == Results ==
  !== Correct Answer - 6 ==   == Spark Answer - 6 ==
   struct<a:int>              struct<a:int>
   [6]                        [6]
  ![7]                        [8]
  ![8]                        [10]
  ![10]                       [9]
  ![9]                        [5]
  ![5]                        [7] (QueryTest.scala:243)


  == Results ==
  !== Correct Answer - 6 ==   == Spark Answer - 6 ==
   struct<a:int>              struct<a:int>
   [6]                        [6]
  ![7]                        [8]
  ![8]                        [10]
  ![10]                       [9]
  ![9]                        [5]
  ![5]                        [7] (QueryTest.scala:243)

  == Results ==
  !== Correct Answer - 6 ==   == Spark Answer - 6 ==
   struct<a:int>              struct<a:int>
   [9]                        [9]
  ![5]                        [7]
  ![6]                        [8]
  ![7]                        [5]
  ![8]                        [6]
   [10]                       [10] (QueryTest.scala:243)
```

**Review by parthchandra — APPROVED** [review]
LGTM

**Comment by viirya** [comment]
Merged. Thanks.
