### PR TITLE
fix: handle type mismatches in native c2r conversion

### LINKED ISSUE #3482: Native c2r bugs
### Describe the bug

```
2026-02-10T20:15:33.1911771Z - select column with default value (native shuffle) *** FAILED *** (4 seconds, 701 milliseconds)
2026-02-10T20:15:33.1915918Z   org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 92.0 failed 1 times, most recent failure: Lost task 0.0 in stage 92.0 (TID 162) (localhost executor driver): org.apache.comet.CometNativeException: Comet Internal Error: Failed to downcast to Date32Array, actual type: Int32
2026-02-10T20:15:33.1921615Z 	at org.apache.comet.Native.columnarToRowConvert(Native Method)
2026-02-10T20:15:33.1924692Z 	at org.apache.comet.NativeColumnarToRowConverter.convert(NativeColumnarToRowConverter.scala:93)
2026-02-10T20:15:33.1927116Z 	at org.apache.spark.sql.comet.CometNativeColumnarToRowExec.$anonfun$doExecute$3(CometNativeColumnarToRowExec.scala:211)
2026-02-10T20:15:33.1928952Z 	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
```

```
2026-02-10T20:15:33.1911771Z - select column with default value (native shuffle) *** FAILED *** (4 seconds, 701 milliseconds)
2026-02-10T20:15:33.1915918Z   org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 92.0 failed 1 times, most recent failure: Lost task 0.0 in stage 92.0 (TID 162) (localhost executor driver): org.apache.comet.CometNativeException: Comet Internal Error: Failed to downcast to Date32Array, actual type: Int32
2026-02-10T20:15:33.1921615Z 	at org.apache.comet.Native.columnarToRowConvert(Native Method)
2026-02-10T20:15:33.1924692Z 	at org.apache.comet.NativeColumnarToRowConverter.convert(NativeColumnarToRowConverter.scala:93)
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by andygrove**
Closes #3482

## Summary

- Fixes native columnar-to-row conversion crash when Spark generates default column values with physical types (e.g. `Int32`) that differ from logical schema types (e.g. `Date32`)
- Changes the fallback arm in `maybe_cast_to_schema_type` to attempt an Arrow cast for any type mismatch, rather than silently passing through the mismatched array
- This prevents similar issues for other data types in the future
- Confirmed that the fuzz test suite now passes when native C2R is enabled

### CODE REVIEW

File: spark/src/main/scala/org/apache/spark/sql/comet/CometNativeColumnarToRowExec.scala [hunk 1]
```diff
@@ -232,11 +232,6 @@ case class CometNativeColumnarToRowExec(child: SparkPlan)
 
 object CometNativeColumnarToRowExec {
 
-  /**
-   * Checks if native columnar to row conversion is enabled.
-   */
-  def isEnabled: Boolean = CometConf.COMET_NATIVE_COLUMNAR_TO_ROW_ENABLED.get()
```
Comment (andygrove) [inline spark/src/main/scala/org/apache/spark/sql/comet/CometNativeColumnarToRowExec.scala:238]: This was unused

File: native/core/src/execution/columnar_to_row.rs [hunk 2]
```diff
@@ -1068,7 +1068,19 @@ impl ColumnarToRowContext {
                     })?;
                 Ok(Arc::new(decimal_array))
             }
-            _ => Ok(Arc::clone(array)),
+            _ => {
+                // For any other type mismatch, attempt an Arrow cast.
+                // This handles cases like Int32 → Date32 (which can happen when Spark
+                // generates default column values using the physical storage type rather
+                // than the logical type).
+                let options = CastOptions::default();
```
Comment (comphead) [inline native/core/src/execution/columnar_to_row.rs:1076]: this might be expensive to create each time, especially the formatter factory?
can it be const?

Comment (andygrove) [reply native/core/src/execution/columnar_to_row.rs:1076]: Claude says that this is cheap and that there are no heap allocations.

```
CastOptions::default() is just setting a bool and a struct of Option::None fields on the stack. There are no heap allocations. The actual cost is entirely in cast_with_options itself (which processes the array data). Creating the options struct is negligible.
```

**Comment by andygrove** [comment]
Thanks @comphead

File: native/core/src/execution/columnar_to_row.rs (hunk 2 above)
Comment (comphead) [reply native/core/src/execution/columnar_to_row.rs:1076]: Btw, DF comes with predefined const 
https://github.com/apache/datafusion/blob/387e20cc58ae91da3902b58438a0684998d7b45b/datafusion/common/src/format.rs#L33
