### PR TITLE
fix: Final aggregation should not bind to the input of partial aggregation

### LINKED ISSUE #156: Final aggregation should not bind to the input of partial aggregation
### Describe the bug

We now bind aggregate expressions to the input of partial aggregate for `HashAggregate` no matter what the mode is.  However, the output of partial aggregate is not same as its input. This incorrect binding will cause unmatched column index. Currently it doesn't expose issues because we don't check the index of bound reference in native side, and the bound columns in aggregate expressions are not used.

However, this is a potential bug and causes some issues when starting to check the index of bound reference. For example, when I work on SortMergeJoin, the operator needs the check to make sure join keys are bound to correct schema.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #156.

## Rationale for this change

We now bind aggregate expressions to the input of partial aggregate for `HashAggregate` no matter what the mode is.  However, the output of partial aggregate is not same as its input. This incorrect binding will cause unmatched column index. Currently it doesn't expose issues because we don't check the index of bound reference in native side, and the bound columns in aggregate expressions are not used.

However, this is a potential bug and causes some issues when starting to check the index of bound reference.

## What changes are included in this PR?

This patch adds the check of the index of bound reference. The aggregate expressions of final aggregation are not bound to the input of partial aggregation anymore but sent to native side as unbound expressions.

### CODE REVIEW

**Comment by viirya** [comment]
cc @huaxingao

**Comment by viirya** [comment]
cc @sunchao

**Review by huaxingao — APPROVED** [review]
LGTM. Thanks for catching the problem.

File: spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala [hunk 1]
```diff
@@ -38,6 +38,25 @@ import org.apache.comet.CometSparkSessionExtensions.isSpark34Plus
  * Test suite dedicated to Comet native aggregate operator
  */
 class CometAggregateSuite extends CometTestBase with AdaptiveSparkPlanHelper {
+  import testImplicits._
+
+  test("Final aggregation should not bind to the input of partial aggregation") {
```
Comment (sunchao) [inline spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala:43]: hmm does this test the issue in this PR? seems it passes in the `main` branch without the fix.

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala [hunk 2]
```diff
@@ -330,26 +333,44 @@ object QueryPlanSerde extends Logging with ShimQueryPlanSerde {
...
+   */
+  def exprToProtoInternal(
+      expr: Expression,
+      inputs: Seq[Attribute],
+      binding: Boolean): Option[Expr] = {
     SQLConf.get
     expr match {
       case a @ Alias(_, _) =>
-        exprToProtoInternal(a.child, inputs)
+        exprToProtoInternal(a.child, inputs, binding)
```
Comment (sunchao) [inline spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:365]: Instead of changing all these, we can probably just move `exprToProtoInternal` and its friends into `exprToProto`. This also prevents it from being called accidentally outside.

File: spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala (hunk 1 above)
Comment (viirya) [reply spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala:43]: After adding the bound index check, it fails. It passes now because we don't have the check now. As I mentioned in the description, the bound is incorrect but because we don't check it, it is not exposed.

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala (hunk 2 above)
Comment (viirya) [reply spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:365]: I don't get your point.

Comment (viirya) [reply spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:365]: You mean we remove `exprToProtoInternal`?

File: spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala (hunk 1 above)
Comment (viirya) [reply spark/src/test/scala/org/apache/comet/exec/CometAggregateSuite.scala:43]: Btw, we need to add the bound check as required for SortMergeJoin work. In that work, it checks joining keys bindings internally in DataFusion. Which checks both binding index and binding column name. So we need to bind column reference to input schema.

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala (hunk 2 above)
Comment (sunchao) [reply spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:365]: Oh I mean move it inside `exprToProto`:

```scala
def exprToProto(...) {
  def exprToProtoInternal(...) { }
  ...
}
```

Comment (viirya) [reply spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:365]: Oh I see. You don't want `exprToProtoInternal` to be called outside?

Comment (sunchao) [reply spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:365]: Right, I think it shouldn't be called directly except by `exprToProto` or itself.

Comment (viirya) [reply spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:365]: Okay

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala [hunk 3]
```diff
@@ -330,1243 +333,1263 @@ object QueryPlanSerde extends Logging with ShimQueryPlanSerde {
...
-        val rightExpr = exprToProtoInternal(Cast(substr, StringType), inputs)
-        scalarExprToProto("strpos", leftExpr, rightExpr)
+        case attr: AttributeReference =>
+          val dataType = serializeDataType(attr.dataType)
 
-      case StringRepeat(str, times) =>
-        val leftExpr = exprToProtoInternal(Cast(str, StringType), inputs)
-        val rightExpr = exprToProtoInternal(Cast(times, LongType), inputs)
-        scalarExprToProto("repeat", leftExpr, rightExpr)
+          if (dataType.isDefined) {
```
Comment (sunchao) [inline spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:1053]: Hmm is the `binding` change accidentally removed?

Comment (viirya) [reply spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:1053]: Oh, yea.

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by viirya** [comment]
Merged. Thanks.
