### PR TITLE
fix: enable arrays_overlap

### LINKED ISSUE #2036: arrays_overlap inconsistent behaviour on two arrays with NULL values
### Describe the bug

Spark doc says:

arrays_overlap(a1, a2) - Returns true if a1 contains at least a non-null element present also in a2.
**If the arrays have no common element and they are both non-empty and either of them contains a null element null is returned**, false otherwise.
https://spark.apache.org/docs/latest/api/sql/index.html#arrays_overlap

But comet returns True instead of NULL if the arrays intersect only by NULL

### Steps to reproduce

```python
#change this to your path
comet_jar_path = "/home/x/comet-spark-spark3.5_2.12-0.9.0.jar"

from pyspark.sql import SparkSession

# uncomment to reproduce vanilla spark behavior:
#spark = SparkSession.builder.appName("test").getOrCreate()

# comment if upper is uncommented
spark = SparkSession.builder.appName("test")\
    .config("spark.jars", comet_jar_path)\
    .config("spark.driver.extraClassPath", comet_jar_path)\
    .config("spark.executor.extraClassPath", comet_jar_path)\
    .config("spark.plugins", "org.apache.spark.CometPlugin")\
    .config("spark.shuffle.manager", "org.apache.spark.sql.comet.execution.shuffle.CometShuffleManager")\
    .config("spark.comet.explainFallback.enabled", "true")\
    .config("spark.comet.expression.allowIncompatible", "true")\
    .getOrCreate()

df = spark.createDataFrame([
    (["a", None], ["b", "c", None]),
    ], ['x', 'y']
)

df.write.mode("overwrite").save("/tmp/tmp_parquet")
spark.read.parquet("/tmp/tmp_parquet").createOrReplaceTempView("t1")

spark.sql("select * from t1").show()
spark.sql("SELECT arrays_overlap(x, y) from t1").show()
spark.sql("SELECT arrays_overlap(x, y) from t1").explain(True)
```

comet returns true if the arrays intersect only by NULL value:
```
+---------+------------+
|        x|           y|
+---------+------------+
|[a, NULL]|[b, c, NULL]|
+---------+------------+

+--------------------+
|arrays_overlap(x, y)|
+--------------------+
|                true|
+--------------------+

== Physical Plan ==
*(1) CometColumnarToRow
+- CometProject [arrays_overlap(x, y)#56], [arrays_overlap(x#34, y#35) AS arrays_overlap(x, y)#56]
   +- CometScan parquet [x#34,y#35] Batched: true, DataFilters: [], Format: CometParquet, Location: InMemoryFileIndex(1 paths)[file:/tmp/tmp_parquet], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<x:array<string>,y:array<string>>
```

### Expected behavior

spark 3.5.6 returns NULL if the arrays intersect only by NULL value:
```
+---------+------------+
|        x|           y|
+---------+------------+
|[a, NULL]|[b, c, NULL]|
+---------+------------+

+--------------------+
|arrays_overlap(x, y)|
+--------------------+
|                NULL|
+--------------------+
```

### Additional context

This is because the `arrays_overlap` call propagates to datafusion `` call, which returns True in this case
Maybe it needs to be changed in datafusion
https://github.com/apache/datafusion/blob/8a3ea8739c36e5cafffff195ffc42ae1fc1e8dde/datafusion/functions-nested/src/array_has.rs#L652
Because if not, then there is no good solution to provide compartibility

### LINKED ISSUE #3175: [Incompatibility] Document arrays_overlap null handling differences
## Summary

`arrays_overlap` is marked as `Incompatible` in Comet, but the specific incompatibility is not documented. This issue tracks documenting and potentially fixing the behavior difference.

## Spark Specification

According to Spark's `arrays_overlap` behavior:
- Returns `true` if at least one element exists in both arrays
- Returns `false` if no common elements are found AND no null elements exist
- Returns `null` if no common elements are found BUT null elements exist in either array (three-valued logic)

Examples:
```sql
SELECT arrays_overlap(array(1, 2, 3), array(3, 4, 5));
-- Spark returns: true

SELECT arrays_overlap(array(1, 2), array(3, 4));  
-- Spark returns: false

SELECT arrays_overlap(array(1, null, 3), array(4, 5));
-- Spark returns: null (because null element exists, result is indeterminate)

SELECT arrays_overlap(array(1, null, 3), array(1, 4));
-- Spark returns: true (found common element 1)
```

## Current Comet Behavior

Comet uses DataFusion's `array_has_any` function. The specific null handling behavior may differ:
- DataFusion may return `false` instead of `null` when no overlap is found but nulls exist

## Current Tests

Looking at `CometArrayExpressionSuite.scala`:
```scala
checkSparkAnswerAndOperator(sql(
  "SELECT arrays_overlap(array('a', null), array('b', null)) from t1 where _1 is not null"))
```

Tests exist but the expression is marked as `Incompatible`, requiring `allow_incompatible=true` to run.

## Possible Solutions

1. **Verify actual behavior difference** - run specific test cases comparing Spark vs Comet
2. **Custom Rust implementation** if DataFusion doesn't match Spark's three-valued null logic
3. **Post-processing** - wrap result to check for null elements and convert false to null

---

> **Note:** This issue was generated with AI assistance.

### LINKED ISSUE #3645: `array_overlap` correctness issue
### Describe the bug

Error executing SQL 'SELECT arrays_overlap(a, b) FROM test_arrays_overlap'

```
== Results ==
!== Correct Answer - 5 ==               == Spark Answer - 5 ==
 struct<arrays_overlap(a, b):boolean>   struct<arrays_overlap(a, b):boolean>
 [false]                                [false]
 [false]                                [false]
 [null]                                 [null]
![null]                                 [true]
 [true]                                 [true]
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kazuyukitanimura**
## Which issue does this PR close?

Closes #3645
Closes #2036
Closes #3175

### CODE REVIEW

File: spark/src/test/scala/org/apache/comet/CometArrayExpressionSuite.scala [hunk 1]
```diff
@@ -545,27 +545,59 @@ class CometArrayExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelp
...
+          checkSparkAnswerAndOperator(sql(
+            "SELECT arrays_overlap(array('a', null), array('b', null)) from t1 where _1 is not null"))
+          checkSparkAnswerAndOperator(spark.sql(
+            "SELECT arrays_overlap((CASE WHEN _2 =_3 THEN array(_6, _7) END), array(_6, _7)) FROM t1"));
         }
       }
     }
   }
 
+  test("arrays_overlap - null handling behavior verification") {
```
Comment (kazuyukitanimura) [inline spark/src/test/scala/org/apache/comet/CometArrayExpressionSuite.scala:561]: Copied from https://github.com/apache/datafusion-comet/pull/3364

**Comment by kazuyukitanimura** [comment]
Looks like we need DF53 https://github.com/apache/datafusion-comet/pull/3629

**Review by comphead — APPROVED** [review]
Thanks @kazuyukitanimura tests looks very complete, we need to backport changes to DF one day
