### PR TITLE
test: ceil and floor works correctly for Decimal128

### LINKED ISSUE #1729: Processing logic of the function `ceil`/`floor` for Decimal128 datatype seems to be wrong
### Describe the bug

While adding unit tests for `ceil`/`floor` I accidentally discovered this issue, it seems like this is an error

### Steps to reproduce

Refer PR #1728 (comment [here](https://github.com/apache/datafusion-comet/pull/1728#discussion_r2082843668))

### Expected behavior

All unit tests will PASS

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kazuyukitanimura**
## Which issue does this PR close?

Closes #1729

## Rationale for this change

#1729 was opened due to PR #1728 (comment https://github.com/apache/datafusion-comet/pull/1728#discussion_r2082843668)
Later #3675 disabled `ceil` and `floor` for decimals.

However, the rust test cases added in #1728 are incorrect in my opinion. When spark `ceil`/`floor`, Spark changes precision and scale. And later result precision and scale are set at https://github.com/apache/datafusion-comet/blob/main/native/spark-expr/src/math_funcs/ceil.rs#L51
The output of `decimal_ceil_f` is intermediate result. Therefore. `decimal_ceil_f` is correct and the expected values of rust test cases are incorrect.

## What changes are included in this PR?

Corrected the rust test cases. Enabled `ceil` and `floor` again

### CODE REVIEW

File: native/spark-expr/src/math_funcs/ceil.rs [hunk 1]
```diff
@@ -178,9 +177,9 @@ mod test {
             unreachable!()
         };
         let expected = Decimal128Array::from(vec![
-            Some(12400),  // 124.00
-            Some(12500),  // 125.00
-            Some(-12900), // -129.00
+            Some(124),  // 124.00
+            Some(125),  // 125.00
+            Some(-129), // -129.00
```
Comment (andygrove) [inline native/spark-expr/src/math_funcs/ceil.rs:181]: Do the comments need updating? 124 becomes 1.24?

Comment (kazuyukitanimura) [reply native/spark-expr/src/math_funcs/ceil.rs:181]: Thanks, actually the precision and scale settings are incorrect, and forgot to update.
So the comments are correct. Fixed the precision and scale in the tests

File: spark/src/test/resources/sql-tests/expressions/math/ceil.sql [hunk 2]
```diff
@@ -15,7 +15,6 @@
 -- specific language governing permissions and limitations
 -- under the License.
 
--- Config: spark.comet.expression.Ceil.allowIncompatible=true
 -- ConfigMatrix: parquet.enable.dictionary=false,true
```
Comment (andygrove) [inline spark/src/test/resources/sql-tests/expressions/math/ceil.sql:19]: nit: It would be nice to add a decimal column to the SQL test data so that decimal ceil/floor is tested through the SQL file framework too. Something like adding a decimal(5,2) column to the test table

**Comment by kazuyukitanimura** [comment]
Thanks @andygrove I have added decimal columns to ceil/floor sql
Once it passes CI, I plan to merge this

File: spark/src/test/resources/sql-tests/expressions/math/ceil.sql (hunk 2 above)
Comment (kazuyukitanimura) [reply spark/src/test/resources/sql-tests/expressions/math/ceil.sql:19]: added

**Comment by kazuyukitanimura** [comment]
Merged, thanks @andygrove
