### PR TITLE
fix: Comet should not fail on negative limit parameter

### LINKED ISSUE #287: Comet fails on limit operator with negative limit parameter
### Describe the bug

Another Spark SQL test failure when working in #250.

DataFrameSuite:
```
- offset *** FAILED *** (36 milliseconds)
[info]   org.apache.spark.SparkException: [INTERNAL_ERROR] The Spark SQL phase planning failed with an internal error. You hit a bug in Spark or the Spark plugins you use. Please, report this bug to the corresponding communities or vendors, and provide the full stack trace.
[info]   at org.apache.spark.SparkException$.internalError(SparkException.scala:88)
...
  Cause: java.lang.AssertionError: assertion failed: limit should be greater or equal to zero
[info]   at scala.Predef$.assert(Predef.scala:223)
[info]   at org.apache.comet.serde.QueryPlanSerde$.operator2Proto(QueryPlanSerde.scala:1847)
[info]   at org.apache.comet.CometSparkSessionExtensions$CometExecRule.org$apache$comet$CometSparkSessionExtensions$CometExecRule$$transform1$1(CometSparkSessionExtensions.scala:232)
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #287.

### CODE REVIEW

**Comment by viirya** [comment]
cc @sunchao @andygrove

**Review by sunchao — APPROVED** [review]

File: spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala [hunk 1]
```diff
@@ -60,6 +60,15 @@ class CometExecSuite extends CometTestBase {
     }
   }
 
+  test("offset") {
+    assume(isSpark34Plus, "Dataset.offset is not available before Spark 3.4")
+    withSQLConf(CometConf.COMET_COLUMNAR_SHUFFLE_ENABLED.key -> "true") {
+      checkSparkAnswer(testData.offset(90))
+      checkSparkAnswer(arrayData.toDF().offset(99))
+      checkSparkAnswer(mapData.toDF().offset(99))
+    }
```
Comment (viirya) [inline spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala:69]: Hmm, `Dataset.offset` is a 3.4+ API. `isSpark34Plus` cannot make this test buildable with 3.2/3.3. 🤔

File: spark/src/test/spark-3.4/org/apache/comet/exec/CometExec3_4Suite.scala [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+  }
+
+  // Dataset.offset API is not available before Spark 3.4
+  test("offset") {
+    withSQLConf(CometConf.COMET_COLUMNAR_SHUFFLE_ENABLED.key -> "true") {
+      checkSparkAnswer(testData.offset(90))
+      checkSparkAnswer(arrayData.toDF().offset(99))
+      checkSparkAnswer(mapData.toDF().offset(99))
+    }
+  }
```
Comment (viirya) [inline spark/src/test/spark-3.4/org/apache/comet/exec/CometExec3_4Suite.scala:51]: Because `Dataset.offset` API is only available on Spark 3.4+. I cannot have this test in `CometExecSuite` which will be built in Spark 3.2 and 3.3. So I move it to a 3.4 specific test suite.

File: spark/src/test/spark-3.4/org/apache/comet/exec/CometExec3_4Suite.scala [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+import org.apache.comet.CometConf
+
+/**
+ * This test suite contains tests for only Spark 3.4.
+ */
+class CometExec3_4Suite extends CometTestBase {
+  import testImplicits._
+
+  override protected def test(testName: String, testTags: Tag*)(testFun: => Any)(implicit
+                                                                                 pos: Position): Unit = {
```
[the remark this answers is not in the document]
Comment (viirya) [reply spark/src/test/spark-3.4/org/apache/comet/exec/CometExec3_4Suite.scala]: Fixed.

**Comment by viirya** [comment]
Merged. Thanks.
