### PR TITLE
fix: add scalar support for bit_count expression

### LINKED ISSUE #3341: Native engine panics on scalar bit_count()
## Description

When Spark's `ConstantFolding` optimizer rule is disabled, an all-literal `bit_count()` call reaches the native engine, which panics with:

```
shouldn't go to bitwise count scalar path.
```

## How to Reproduce

```sql
SET spark.sql.optimizer.excludedRules=org.apache.spark.sql.catalyst.optimizer.ConstantFolding;
SELECT bit_count(7);
```

## Expected Behavior

The native engine should handle scalar bit_count inputs gracefully — either by computing the correct result or by falling back to Spark, not by panicking.

### PR DESCRIPTION
**Pull request by hsiang-c**
The bit_count function now handles scalar inputs in addition to arrays. Scalar inputs return scalar outputs, maintaining proper type semantics.

Enable bit_count tests in bitwise.sql

## Which issue does this PR close?

Closes #3341 

## Rationale for this change

Current implementation doesn't take scalar input.

## What changes are included in this PR?

- Handle scalar input of type `Boolean`, `Byte`, `Short`, `Integer` and `Long` like [Spark](https://github.com/apache/spark/blob/branch-4.1/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/bitwiseExpressions.scala#L230) does.

## How are these changes tested?

- unit test
- SQL test

### CODE REVIEW

File: spark/src/test/resources/sql-tests/expressions/bitwise/bitwise.sql [hunk 1]
```diff
@@ -73,7 +73,7 @@ SELECT bit_get(i, pos) FROM test_bit_get
 query
 SELECT 1111 & 2, 1111 | 2, 1111 ^ 2
 
-query ignore(https://github.com/apache/datafusion-comet/issues/3341)
+query spark_answer_only
```
Comment (andygrove) [inline spark/src/test/resources/sql-tests/expressions/bitwise/bitwise.sql]: These tests should not need `spark_answer_only` if they are now running correctly in Comet?

```suggestion
query
```

**Comment by parthchandra** [comment]
Could you rebase? Otherwise this looks good.
