### PR TITLE
fix: substring with negative start index

### LINKED ISSUE #3337: Native engine panics on all-scalar inputs for Substring and StringSpace
## Description

When Spark's `ConstantFolding` optimizer rule is disabled, all-scalar (literal-only) expressions reach Comet's native engine. The native engine panics with:

- `Substring(scalar) should be fold in Spark JVM side.`
- `StringSpace(scalar) should be fold in Spark JVM side.`

## How to Reproduce

```sql
SET spark.sql.optimizer.excludedRules=org.apache.spark.sql.catalyst.optimizer.ConstantFolding;
SELECT substring('hello world', 1, 5);
SELECT space(5);
SELECT left('hello', 3);
```

## Expected Behavior

The native engine should handle scalar inputs gracefully — either by computing the correct result or by falling back to Spark, not by panicking.

## Affected Expressions

- `substring()` / `left()`
- `space()`

### LINKED ISSUE #3919: substring incompatible with spark for negative start index
### Describe the bug

Upstream bug: https://github.com/apache/datafusion/issues/21510

Add these tests to `substring.sql`:

```
query
SELECT substring(s, -2, 3) FROM test_substring

query
SELECT substring(s, -10, 3) FROM test_substring

query
SELECT substring(s, -300, 3) FROM test_substring
```

Example failure:

```
== Results ==
!== Correct Answer - 4 ==              == Spark Answer - 4 ==
 struct<substring(s, -10, 3):string>   struct<substring(s, -10, 3):string>
 []                                    []
![]                                    [abc]
 [ell]                                 [ell]
 [null]                                [null]
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kazuyukitanimura**
## Which issue does this PR close?

Closes #3919
Closes #3337

### CODE REVIEW

File: native/spark-expr/src/string_funcs/substring.rs [hunk 1]
```diff
@@ -113,3 +119,629 @@ impl PhysicalExpr for SubstringExpr {
...
+            }
+            Ok(Arc::new(builder.finish()) as ArrayRef)
+        }
+        DataType::Dictionary(_, _) => {
+            let dict = as_dictionary_array::<Int32Type>(array);
+            let values = spark_substring_negative_start(dict.values(), start, len)?;
+            let result = DictionaryArray::try_new(dict.keys().clone(), values)?;
+            Ok(Arc::new(result) as ArrayRef)
+        }
+        _ => Ok(Arc::clone(array)),
```
Comment (andygrove) [inline native/spark-expr/src/string_funcs/substring.rs]: Should this be an error rather than just returning the input data?

File: native/spark-expr/src/string_funcs/substring.rs [hunk 2]
```diff
@@ -113,3 +119,629 @@ impl PhysicalExpr for SubstringExpr {
...
+                        bin_array.value(i),
+                        start,
+                        len,
+                    ));
+                }
+            }
+            Ok(Arc::new(builder.finish()) as ArrayRef)
+        }
+        DataType::Dictionary(_, _) => {
+            let dict = as_dictionary_array::<Int32Type>(array);
```
Comment (andygrove) [inline native/spark-expr/src/string_funcs/substring.rs:193]: This would panic for a dictionary with `Int64Type`. Can we add a check for the type?

File: native/spark-expr/src/string_funcs/substring.rs [hunk 3]
```diff
@@ -113,3 +119,629 @@ impl PhysicalExpr for SubstringExpr {
...
+
+    if start >= end {
+        return String::new();
+    }
+
+    s.chars()
+        .skip(start as usize)
+        .take((end - start) as usize)
+        .collect()
+}
```
Comment (andygrove) [inline native/spark-expr/src/string_funcs/substring.rs]: Claude recommended an optimized version to avoid an intermediate string allocation per row. I have not verified.

```rust
fn spark_substr_negative(s: &str, pos: i64, len: u64) -> &str {                                                                                                                                                        
      let num_chars = s.chars().count() as i64;                              
      let end = (num_chars + pos).saturating_add(len as i64).min(num_chars);                                                                                                                                             
      let start = (num_chars + pos).max(0);
      if start >= end {                                                                                                                                                                                                  
          return "";                                                                                                                                                                                                     
      }
                                                                                                                                                                                                                         
      // Translate char indices [start, end) to byte offsets in a single forward pass.                                                                                                                                   
      let mut it = s.char_indices();
      let byte_start = it.by_ref().nth(start as usize).map(|(b, _)| b).unwrap_or(s.len());                                                                                                                               
      let span = (end - start - 1) as usize;                                                                                                                                                                             
      let byte_end = it.nth(span).map(|(b, _)| b).unwrap_or(s.len());
                                                                                                                                                                                                                         
      &s[byte_start..byte_end]                                               
  }         
```

File: native/spark-expr/src/string_funcs/substring.rs (hunk 2 above)
Comment (kazuyukitanimura) [reply native/spark-expr/src/string_funcs/substring.rs:193]: Parquet dictionary uses Integer, so we are not doing `Int64Type` including other locations. E.g.https://github.com/apache/datafusion-comet/blob/main/native/spark-expr/src/static_invoke/char_varchar_utils/read_side_padding.rs#L68

File: native/spark-expr/src/string_funcs/substring.rs (hunk 1 above)
Comment (kazuyukitanimura) [reply native/spark-expr/src/string_funcs/substring.rs]: Thank you, updated

File: native/spark-expr/src/string_funcs/substring.rs (hunk 3 above)
Comment (kazuyukitanimura) [reply native/spark-expr/src/string_funcs/substring.rs]: Updated

File: spark/src/test/resources/sql-tests/expressions/string/substring.sql [hunk 4]
```diff
@@ -39,6 +39,153 @@ SELECT substring(s, 1, -1) FROM test_substring
...
+
+-- scalar multi-byte
+query
+SELECT substring('こんにちは世界', 1, 3)
+
+query
+SELECT substring('こんにちは世界', -2)
+
+query
+SELECT substring('🎉🎊🎈🎁', 2, 2)
```
Comment (comphead) [inline spark/src/test/resources/sql-tests/expressions/string/substring.sql:177]: 👍

**Review by comphead — APPROVED** [review]
Thanks @kazuyukitanimura I think we also would need to donate this later to DF

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @kazuyukitanimura.

nit: there is some overlap between the Scala and SQL tests, and the SQL tests may have been sufficient alone, but we can review laster

**Comment by comphead** [comment]
Turns out DF has spark impl for `substring` but it was incorrect for negative use cases https://github.com/apache/datafusion/pull/21963
