### PR TITLE
fix: scalar subquery pushdown and reuse for CometNativeScanExec (SPARK-43402)

### LINKED ISSUE #4042: native_datafusion: scalar subquery pushdown does not produce ReusedSubqueryExec
## Summary

With `native_datafusion`, a scalar subquery pushed down as a data filter on `CometNativeScanExec` does not produce a `ReusedSubqueryExec` the way Spark's vectorized reader (and `CometScanExec`) do. The pushed subquery is a plain `Subquery`, so subsequent references to the same subquery do not share the result.

## Failing Test

`SubquerySuite`: "SPARK-43402: FileSourceScanExec supports push down data filter with scalar subquery"

## Reproduction

Updating the test's plan-match to include `CometNativeScanExec`:

```scala
val dataSourceScanExec = collect(df.queryExecution.executedPlan) {
  case f: FileSourceScanLike => f
  case c: CometScanExec => c
  case n: CometNativeScanExec => n
}
```

makes the first assertion (`dataSourceScanExec.size == 1`) pass. The next assertion still fails:

```
was not instance of org.apache.spark.sql.execution.ReusedSubqueryExec (SubquerySuite.scala:2716)
```

with the plan showing a plain `Subquery` rather than `ReusedSubqueryExec`:

```
Subquery subquery#295, [id=#166]
+- AdaptiveSparkPlan isFinalPlan=true
   +- == Final Plan ==
      ResultQueryStage 2
      +- CometNativeColumnarToRow
         +- CometHashAggregate [min#303], Final, [min(c2#297)]
            +- ShuffleQueryStage 0
               +- CometExchange SinglePartition, ...
                  +- CometHashAggregate [c2#297], Partial, [partial_min(c2#297)]
                     +- CometNativeScan parquet ...
```

The `dataFilters` on the `CometNativeScanExec` carry the subquery reference but aren't wired into the reused-subquery machinery.

## Related

Split from #3315 while triaging the tests previously ignored under #3321.

### PR DESCRIPTION
**Pull request by mbutrovich**
## Which issue does this PR close?

Closes #4042.

## Rationale for this change

SPARK-43402 (Spark 4.0) pushes `ScalarSubquery` into `FileSourceScanExec.dataFilters` for Parquet filter pushdown. When `CometScanRule` replaces the scan with `CometNativeScanExec`, the subquery in `dataFilters` becomes a second copy (the first is in the filter expression above). Spark's `ReuseSubquery` rules should deduplicate these, but two issues prevented it:

1. `CometNativeScanExec.equals` did not include `dataFilters`, so Spark's `transformAllExpressionsWithPruning` silently dropped expression transformations on that field (it uses `fastEquals` to detect changes).
2. In AQE, Spark's `ReuseAdaptiveSubquery` runs before Comet's node replacements (`CometScanRule`/`CometExecRule`), so the reuse it applies gets lost when Comet copies expressions from the original Spark nodes.

Without the fix, the subquery executes twice and `ReusedSubqueryExec` is never produced.

## What changes are included in this PR?

**`CometNativeScanExec.equals`/`hashCode`**: Added `dataFilters` so expression transformations (subquery reuse, etc.) are detected by Spark's tree traversal.

**`CometReuseSubquery`**: New `queryStageOptimizerRule` that re-applies subquery deduplication after Comet node conversions in AQE. Same algorithm as Spark's `ReuseExchangeAndSubquery` (subquery portion): top-down traversal, caching by canonical form. For non-AQE, Spark's `ReuseExchangeAndSubquery` already runs after columnar rules and handles reuse correctly.

**Scalar subquery execution-time pushdown**: `CometNativeScanExec.serializedPartitionData` resolves `ScalarSubquery` to `Literal` at execution time and appends the resolved filter to the `NativeScanCommon` protobuf. Same approach as `FileSourceScanLike.pushedDownFilters` in `DataSourceScanExec.scala`.

**Shim split**: `ShimCometSparkSessionExtensions` moved from `spark-3.x/` to `spark-3.4/` (no-op for `injectQueryStageOptimizerRule`) and `spark-3.5/` (calls API). `injectQueryStageOptimizerRule` was added in Spark 3.5 (SPARK-45785).

**Rule ordering documentation**: Added pipeline diagram to `CometSparkSessionExtensions` class doc covering both AQE and non-AQE rule execution order.

**4.0.1.diff**: Unignored `SubquerySuite` SPARK-43402 test, added `CometNativeScanExec` to scan matching.

## How are these changes tested?

New test in `CometExecSuite`: "scalar subquery in data filters does not break subquery reuse" (Spark 4.0 only, both AQE on/off). Verifies correct results via `checkSparkAnswer`, `ScalarSubquery` presence in `dataFilters`, `ReusedSubqueryExec` in the plan, and `numFiles` metric. Mirrors Spark's `SubquerySuite` SPARK-43402 test assertions.

### CODE REVIEW

File: spark/src/main/scala/org/apache/comet/rules/CometReuseSubquery.scala [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+ *
+ * For non-AQE, Spark's ReuseExchangeAndSubquery runs after ApplyColumnarRulesAndInsertTransitions
+ * in QueryExecution.preparations and handles reuse correctly without this rule.
+ *
+ * @see
+ *   ReuseExchangeAndSubquery (Spark's non-AQE subquery reuse)
+ * @see
+ *   ReuseAdaptiveSubquery (Spark's AQE subquery reuse)
+ */
+case object CometReuseSubquery extends Rule[SparkPlan] {
```
Comment (andygrove) [inline spark/src/main/scala/org/apache/comet/rules/CometReuseSubquery.scala:48]: We should start thinking about an audit process for areas where we are replicating Spark logic, so that when we upgrade to future versions of Spark we can check that we staying consistent. Maybe a starting point is adding annotations to sections of code where we replicate upstream logic? No action needed on this PR ... just thinking aloud

File: spark/src/main/scala/org/apache/spark/sql/comet/CometNativeScanExec.scala [hunk 2]
```diff
@@ -208,8 +215,41 @@ case class CometNativeScanExec(
...
+            s.updateResult()
+          case _ =>
+        }
+      }
+      val resolvedFilters = scalarSubqueryFilters
+        .map(_.transform { case s: org.apache.spark.sql.execution.ScalarSubquery =>
+          Literal.create(s.eval(null), s.dataType)
+        })
+      if (resolvedFilters.nonEmpty) {
+        import org.apache.comet.serde.QueryPlanSerde.exprToProto
```
Comment (andygrove) [inline spark/src/main/scala/org/apache/spark/sql/comet/CometNativeScanExec.scala]: can this be a file level import?

File: spark/src/main/scala/org/apache/spark/sql/comet/CometNativeScanExec.scala [hunk 3]
```diff
@@ -208,8 +215,41 @@ case class CometNativeScanExec(
...
+        .filter(_.exists(_.isInstanceOf[org.apache.spark.sql.execution.ScalarSubquery]))
+      scalarSubqueryFilters.foreach { f =>
+        f.foreach {
+          case s: org.apache.spark.sql.execution.ScalarSubquery =>
+            s.updateResult()
+          case _ =>
+        }
+      }
+      val resolvedFilters = scalarSubqueryFilters
+        .map(_.transform { case s: org.apache.spark.sql.execution.ScalarSubquery =>
```
Comment (andygrove) [inline spark/src/main/scala/org/apache/spark/sql/comet/CometNativeScanExec.scala]: can an import be used to avoid the fully-qualified names?

**Comment by andygrove** [comment]
I took a first pass through. It makes sense to me. Left some minor comments.

**Review by andygrove — APPROVED** [review]
LGTM pending CI. Thanks @mbutrovich
