### PR TITLE
fix: enable Corr

### LINKED ISSUE #2646: fuzz test failure: `corr` null vs Nan
## SQL
```
SELECT c3, c42, corr(c20, c6) FROM test0 GROUP BY c3,c42 ORDER BY c3, c42;
```
### Spark Plan
```
AdaptiveSparkPlan isFinalPlan=true
+- == Final Plan ==
   *(3) Sort [c3#3 ASC NULLS FIRST, c42#42 ASC NULLS FIRST], true, 0
   +- AQEShuffleRead coalesced
      +- ShuffleQueryStage 1
         +- Exchange rangepartitioning(c3#3 ASC NULLS FIRST, c42#42 ASC NULLS FIRST, 200), ENSURE_REQUIREMENTS, [plan_id=91129]
            +- *(2) HashAggregate(keys=[c3#3, c42#42], functions=[corr(c20#20, c6#6)], output=[c3#3, c42#42, corr(c20, c6)#28057])
               +- AQEShuffleRead coalesced
                  +- ShuffleQueryStage 0
                     +- Exchange hashpartitioning(c3#3, c42#42, 200), ENSURE_REQUIREMENTS, [plan_id=91101]
                        +- *(1) HashAggregate(keys=[c3#3, c42#42], functions=[partial_corr(c20#20, c6#6)], output=[c3#3, c42#42, n#28038, xAvg#28039, yAvg#28040, ck#28041, xMk#28042, yMk#28043])
                           +- *(1) ColumnarToRow
                              +- FileScan parquet [c3#3,c6#6,c20#20,c42#42] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex(1 paths)[file:/home/andy/git/apache/datafusion-comet/fuzz-testing/test0.parquet], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<c3:int,c6:double,c20:double,c42:array<timestamp_ntz>>
+- == Initial Plan ==
   Sort [c3#3 ASC NULLS FIRST, c42#42 ASC NULLS FIRST], true, 0
   +- Exchange rangepartitioning(c3#3 ASC NULLS FIRST, c42#42 ASC NULLS FIRST, 200), ENSURE_REQUIREMENTS, [plan_id=91083]
      +- HashAggregate(keys=[c3#3, c42#42], functions=[corr(c20#20, c6#6)], output=[c3#3, c42#42, corr(c20, c6)#28057])
         +- Exchange hashpartitioning(c3#3, c42#42, 200), ENSURE_REQUIREMENTS, [plan_id=91080]
            +- HashAggregate(keys=[c3#3, c42#42], functions=[partial_corr(c20#20, c6#6)], output=[c3#3, c42#42, n#28038, xAvg#28039, yAvg#28040, ck#28041, xMk#28042, yMk#28043])
               +- FileScan parquet [c3#3,c6#6,c20#20,c42#42] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex(1 paths)[file:/home/andy/git/apache/datafusion-comet/fuzz-testing/test0.parquet], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<c3:int,c6:double,c20:double,c42:array<timestamp_ntz>>

```
### Comet Plan
```
AdaptiveSparkPlan isFinalPlan=true
+- == Final Plan ==
   *(1) CometColumnarToRow
   +- CometSort [c3#3, c42#42, corr(c20, c6)#28174], [c3#3 ASC NULLS FIRST, c42#42 ASC NULLS FIRST]
      +- AQEShuffleRead coalesced
         +- ShuffleQueryStage 1
            +- CometColumnarExchange rangepartitioning(c3#3 ASC NULLS FIRST, c42#42 ASC NULLS FIRST, 200), ENSURE_REQUIREMENTS, CometColumnarShuffle, [plan_id=91263]
               +- CometHashAggregate [c3#3, c42#42, n#28155, xAvg#28156, yAvg#28157, ck#28158, xMk#28159, yMk#28160], Final, [c3#3, c42#42], [corr(c20#20, c6#6)]
                  +- AQEShuffleRead coalesced
                     +- ShuffleQueryStage 0
                        +- CometColumnarExchange hashpartitioning(c3#3, c42#42, 200), ENSURE_REQUIREMENTS, CometColumnarShuffle, [plan_id=91217]
                           +- CometHashAggregate [c3#3, c6#6, c20#20, c42#42], Partial, [c3#3, c42#42], [partial_corr(c20#20, c6#6)]
                              +- CometScan [native_iceberg_compat] parquet [c3#3,c6#6,c20#20,c42#42] Batched: true, DataFilters: [], Format: CometParquet, Location: InMemoryFileIndex(1 paths)[file:/home/andy/git/apache/datafusion-comet/fuzz-testing/test0.parquet], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<c3:int,c6:double,c20:double,c42:array<timestamp_ntz>>
+- == Initial Plan ==
   CometSort [c3#3, c42#42, corr(c20, c6)#28174], [c3#3 ASC NULLS FIRST, c42#42 ASC NULLS FIRST]
   +- CometColumnarExchange rangepartitioning(c3#3 ASC NULLS FIRST, c42#42 ASC NULLS FIRST, 200), ENSURE_REQUIREMENTS, CometColumnarShuffle, [plan_id=91198]
      +- CometHashAggregate [c3#3, c42#42, n#28155, xAvg#28156, yAvg#28157, ck#28158, xMk#28159, yMk#28160], Final, [c3#3, c42#42], [corr(c20#20, c6#6)]
         +- CometColumnarExchange hashpartitioning(c3#3, c42#42, 200), ENSURE_REQUIREMENTS, CometColumnarShuffle, [plan_id=91196]
            +- CometHashAggregate [c3#3, c6#6, c20#20, c42#42], Partial, [c3#3, c42#42], [partial_corr(c20#20, c6#6)]
               +- CometScan [native_iceberg_compat] parquet [c3#3,c6#6,c20#20,c42#42] Batched: true, DataFilters: [], Format: CometParquet, Location: InMemoryFileIndex(1 paths)[file:/home/andy/git/apache/datafusion-comet/fuzz-testing/test0.parquet], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<c3:int,c6:double,c20:double,c42:array<timestamp_ntz>>

```
First difference at row 150:
Spark: `1190973260,[3333-01-21T01:11:48.781],NULL`
Comet: `1190973260,[3333-01-21T01:11:48.781],NaN`

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kazuyukitanimura**
## Which issue does this PR close?

Closes #2646

## Rationale for this change

This is a fix for the behavior for https://github.com/apache/datafusion-comet/issues/2646#issuecomment-3524544102

## What changes are included in this PR?

When both inputs to `Corr` are `NaN`, return `Null`

## How are these changes tested?

Added tests

### CODE REVIEW

**Comment by comphead** [comment]
what exactly the query that failed in spark? I checked DF corr and PGQL corr works the same.

```
> CREATE TABLE test_corr_nan(x double, y double, grp string);
0 row(s) fetched. 
Elapsed 0.025 seconds.

> INSERT INTO test_corr_nan VALUES (cast('NaN' as double), cast('NaN' as double), 'both_nan'), (cast('NaN' as double), 1.0, 'nan_val'), (1.0, cast('NaN' as double), 'val_nan'), (NULL, cast('NaN' as double), 'null_nan'), (cast('NaN' as double), NULL, 'nan_null'), (NULL, NULL, 'both_null'), (NULL, 1.0, 'null_val'), (1.0, NULL, 'val_null');
+-------+
| count |
+-------+
| 8     |
+-------+
1 row(s) fetched. 
Elapsed 0.016 seconds.

> SELECT grp, corr(x, y) FROM test_corr_nan GROUP BY grp ORDER BY grp;
+-----------+---------------------------------------+
| grp       | corr(test_corr_nan.x,test_corr_nan.y) |
+-----------+---------------------------------------+
| both_nan  | NaN                                   |
| both_null | NULL                                  |
| nan_null  | NULL                                  |
| nan_val   | NULL                                  |
| null_nan  | NULL                                  |
| null_val  | NULL                                  |
| val_nan   | NULL                                  |
| val_null  | NULL                                  |
+-----------+---------------------------------------+
8 row(s) fetched. 
Elapsed 0.036 seconds.
```

PGSQL
```
CREATE TABLE test_corr_nan(x float, y float, grp varchar);

INSERT INTO test_corr_nan VALUES (
cast('NaN' as float), cast('NaN' as float), 'both_nan'), (
cast('NaN' as float), 1.0, 'nan_val'), 
(1.0, cast('NaN' as float), 'val_nan'), 
(NULL, cast('NaN' as float), 'null_nan'), 
(cast('NaN' as float), NULL, 'nan_null'), 
(NULL, NULL, 'both_null'), (NULL, 1.0, 'null_val'), (1.0, NULL, 'val_null');


SELECT grp, corr(x, y) FROM test_corr_nan GROUP BY grp ORDER BY grp;

    grp    | corr 
-----------+------
 both_nan  |  NaN
 both_null |     
 nan_null  |     
 nan_val   |     
 null_nan  |     
 null_val  |     
 val_nan   |     
 val_null  |     
(8 rows)

```

**Comment by kazuyukitanimura** [comment]
> what exactly the query that failed in spark?

Thanks @comphead Just to double check, you haven't enabled Comet for Spark?
The original issue is
https://github.com/apache/datafusion-comet/issues/2646#issuecomment-3524544102

**Comment by comphead** [comment]
I have some feeling Comet is not using DF based corr and uses its own implementation 

```
impl AggregateUDFImpl for Correlation 
```

More correct behavior is to delegate this to DF like for count 

```
AggregateExprBuilder::new(count_udaf(), children)
```

**Review by comphead — COMMENTED** [review]
Thanks @kazuyukitanimura I think we need to try to delegate `corr` to DF `correlation::corr_udaf()` and remove Comet old implementation

File: spark/src/test/resources/sql-tests/expressions/aggregate/corr.sql [hunk 1]
```diff
@@ -29,3 +28,13 @@ SELECT corr(x, y) FROM test_corr
 
 query tolerance=1e-6
 SELECT grp, corr(x, y) FROM test_corr GROUP BY grp ORDER BY grp
+
+-- Test permutations of NULL and NaN
+statement
+CREATE TABLE test_corr_nan(x double, y double, grp string) USING parquet
+
+statement
+INSERT INTO test_corr_nan VALUES (cast('NaN' as double), cast('NaN' as double), 'both_nan'), (cast('NaN' as double), 1.0, 'nan_val'), (1.0, cast('NaN' as double), 'val_nan'), (NULL, cast('NaN' as double), 'null_nan'), (cast('NaN' as double), NULL, 'nan_null'), (NULL, NULL, 'both_null'), (NULL, 1.0, 'null_val'), (1.0, NULL, 'val_null')
```
Comment (parthchandra) [inline spark/src/test/resources/sql-tests/expressions/aggregate/corr.sql]: Maybe add a group with mixed nan and valid rows ( eg ` [(NaN, NaN), (1.0, 2.0), (3.0, 4.0)]` )

File: spark/src/main/scala/org/apache/comet/serde/aggregates.scala [hunk 2]
```diff
@@ -584,20 +584,18 @@ object CometStddevPop extends CometAggregateExpressionSerde[StddevPop] with Come
 }
 
 object CometCorr extends CometAggregateExpressionSerde[Corr] {
-
-  override def getSupportLevel(expr: Corr): SupportLevel =
```
Comment (parthchandra) [inline spark/src/main/scala/org/apache/comet/serde/aggregates.scala:588]: Claude flagged some edge cases we can document -
```
 ▎ 1. Legacy mode: When spark.sql.legacy.statisticalAggregate=true, nullOnDivideByZero is false and Spark returns NaN for the n=1 case. With this workaround, Comet would return null instead (because the NaN row gets skipped → n=0). Should we add a getSupportLevel guard that returns Incompatible when
  corr.nullOnDivideByZero is false? Or at least document this?
 ▎ 2. Mixed groups: For a group containing (NaN, NaN) alongside valid pairs like (1.0, 2.0), Spark returns NaN (NaN contaminates the accumulator), while this workaround would skip the NaN row and compute a valid correlation over the remaining rows. Is that a known limitation we're OK with?
 ```

**Review by parthchandra — APPROVED** [review]
lgtm. Suggestions are non-blocking

File: spark/src/test/resources/sql-tests/expressions/aggregate/corr.sql (hunk 1 above)
Comment (andygrove) [reply spark/src/test/resources/sql-tests/expressions/aggregate/corr.sql]: I also was going to suggest adding a group with multiple NaN rows (e.g. 2-3 rows of (NaN, NaN, 'multi_nan')) to make sure the wrapping approach works when n > 1

File: spark/src/main/scala/org/apache/comet/serde/aggregates.scala (hunk 2 above)
Comment (andygrove) [reply spark/src/main/scala/org/apache/comet/serde/aggregates.scala:588]: Same. 

Worth double-checking: the original incompatibility note said "returns null instead of NaN in some edge cases." That also describes the behavior in correlation.rs:evaluate() when stddev is zero (constant values produce stddev=0, Spark returns NaN from 0/0, Comet returns null from the null_on_divide_by_zero guard). Is that case also resolved, or should Incompatible remain for that scenario?

File: spark/src/test/resources/sql-tests/expressions/aggregate/corr.sql (hunk 1 above)
Comment (kazuyukitanimura) [reply spark/src/test/resources/sql-tests/expressions/aggregate/corr.sql]: updated

File: spark/src/main/scala/org/apache/comet/serde/aggregates.scala (hunk 2 above)
Comment (kazuyukitanimura) [reply spark/src/main/scala/org/apache/comet/serde/aggregates.scala:588]: Ended up fixing properly for the legacy mode as well. Added tests too

**Comment by kazuyukitanimura** [comment]
Thanks @comphead @parthchandra @andygrove 
I think I properly fixed this rather than workingaround

**Comment by comphead** [comment]
> Thanks @comphead @parthchandra @andygrove I think I properly fixed this rather than workingaround

I would still try to delegate corr to DF instead of Comet proprietary code, it would make our codebase more lightweight

**Comment by kazuyukitanimura** [comment]
> > Thanks @comphead @parthchandra @andygrove I think I properly fixed this rather than workingaround
> 
> I would still try to delegate corr to DF instead of Comet proprietary code, it would make our codebase more lightweight

There is some behavior differences, so in order to use DF correlation, we need to create Spark expr in DF. Perhaps that will be next time

**Comment by kazuyukitanimura** [comment]
Thanks @comphead @parthchandra @andygrove merged
